import { GameEvent } from '../types';
import {
  HAEUN_EVENTS, JIHUN_EVENTS, SUBIN_EVENTS, MINJAE_EVENTS, YUNA_EVENTS, JUNHA_EVENTS,
  DOYUN_FIRST_MEET_M, DOYUN_FIRST_MEET_F, DOYUN_DAILY, DOYUN_GRADUATION, DOYUN_SCHOOL_SPLIT,
} from './npc';
import {
  SCHOOL_Y1_INTRO, SCHOOL_ELEM_TO_MIDDLE, SCHOOL_MIDDLE_HIGH,
} from './school';
import {
  PRESIDENT_FOLLOWUP, PRESIDENT_ELECTION, PRESIDENT_ONLY, PRESIDENT_NON,
} from './president';
import { RANDOM_EVENTS } from './random';
import { BIRTHDAY_EVENTS } from './birthday';
import { MONEY_SINK_EVENTS } from './money-sink';
import { CRISIS_EVENTS } from './crisis';
import { CAREER_CONFLICT_EVENTS } from './parent-career';
import { ADOLESCENCE_EVENTS } from './parent-adolescence';
import { REACH_EVENTS } from './reach';
import { MID_REACH_EVENTS } from './reachMid';

export const GAME_EVENTS: GameEvent[] = [
  ...SCHOOL_Y1_INTRO,
  ...DOYUN_FIRST_MEET_M,
  ...DOYUN_FIRST_MEET_F,
  ...DOYUN_DAILY,
  ...DOYUN_GRADUATION,
  ...SCHOOL_ELEM_TO_MIDDLE,
  ...DOYUN_SCHOOL_SPLIT,
  ...SCHOOL_MIDDLE_HIGH,
  ...HAEUN_EVENTS,
  ...JIHUN_EVENTS,
  ...SUBIN_EVENTS,
  ...MINJAE_EVENTS,
  ...YUNA_EVENTS,
  ...PRESIDENT_FOLLOWUP,
  ...RANDOM_EVENTS,
  ...PRESIDENT_ELECTION,
  ...PRESIDENT_ONLY,
  ...PRESIDENT_NON,
  ...BIRTHDAY_EVENTS,
  ...JUNHA_EVENTS,

  ...MONEY_SINK_EVENTS,
  ...CRISIS_EVENTS,
  ...CAREER_CONFLICT_EVENTS,
  ...ADOLESCENCE_EVENTS,
  ...REACH_EVENTS,
  ...MID_REACH_EVENTS,
];
