import { GameEvent } from '../types';

// ===== 중학교(Y2~Y4) 친밀도 도달형 이벤트 42개 =====
// v4 확정본(docs/reach-mid-v4-2026-06-12.md) 전사. 5작가 → 10인리뷰 → codex/cursor → 5인재검수.
// week 없음 + condition 게이트(intimacy>=tier && year===Y)로 reach 풀 진입. 페이싱 엔진(getReachForWeek)이
// fresh 즉시 / pre-met 쿨다운 분산 처리. 교내 장면은 !s.isVacation 가드(방학 컨텍스트 desync 방지).
// importance: 진입5/중간6/핵심7. memorySlotDraft는 핵심(memory) 컷에만. recallText 20~35자.

export const MID_REACH_EVENTS = [
  // ===================== 지훈 (jihun) — 소꿉친구·활기=방패 =====================
  {
    id: 'jihun-locker-code',
    reach: { npc: 'jihun', tier: 45, year: 2 },
    title: '사물함 비번',
    description: '사물함 비번을 까먹고 끙끙대자, 지훈이 슬쩍 다가와 네 자리를 눌러 본다.\n"이거 아냐? 네 생일. 친구 생일 정돈 외우지." 별일 아니라는 듯 어깨를 으쓱한다.',
    femaleDescription: '사물함 비번을 까먹고 끙끙대자, 지훈이 슬쩍 다가와 네 생일 네 자리를 눌러 본다.\n"이거 아냐? 작년에 네가 말했잖아." 자기 비번도 네 생일로 맞춰뒀다는 건 끝에 가서야 흘린다.',
    speakers: ['jihun'],
    location: 'hallway',
    background: 'locker_hallway',
    condition: (s) => { const n = s.npcs.find(x => x.id === 'jihun'); return !!n?.met && n.intimacy >= 45 && s.year === 2 && !s.isVacation; },
    choices: [
      { text: '"친구 생일 외우는 거 좀 무섭다?" 놀린다', effects: { social: 1 }, npcEffects: [{ npcId: 'jihun', intimacyChange: 3 }], message: '"외우기 쉬운 날이라 그래, 인마." 지훈이 픽 웃는다.', timeCost: 1 },
      { text: '"고마워, 진짜 까먹을 뻔했어" 솔직히', effects: { mental: 1 }, npcEffects: [{ npcId: 'jihun', intimacyChange: 4 }], message: '"별거 아냐." 말은 그렇게 하면서 입꼬리가 올라간다.', timeCost: 1 },
      { text: '"와, 좀 무섭게 잘 기억하네" 장난스레', effects: { social: 1 }, npcEffects: [{ npcId: 'jihun', intimacyChange: 2 }], message: '"무섭긴 뭐가 무서워." 지훈이 웃으며 사물함을 탁 닫아준다.', timeCost: 1 },
    ],
    femaleChoices: [
      { text: '"너 비번까지 내 생일로 해놨냐?" 놀린다', effects: { social: 1 }, npcEffects: [{ npcId: 'jihun', intimacyChange: 3 }], message: '지훈이 귀를 만지며 딴청을 부린다. "아 그냥… 외우기 쉬워서."', timeCost: 1 },
      { text: '"고마워, 진짜 까먹을 뻔했어" 솔직히', effects: { mental: 1 }, npcEffects: [{ npcId: 'jihun', intimacyChange: 4 }], message: '"별거 아냐." 말은 그렇게 하면서 입꼬리가 올라간다.', timeCost: 1 },
      { text: '"와, 좀 무섭게 잘 기억하네" 장난스레', effects: { social: 1 }, npcEffects: [{ npcId: 'jihun', intimacyChange: 2 }], message: '"무섭긴 뭐가 무서워." 지훈이 웃으며 사물함을 탁 닫아준다.', timeCost: 1 },
    ],
  },
  {
    id: 'jihun-mirror-height',
    reach: { npc: 'jihun', tier: 55, year: 2 },
    title: '거울 속 키차이',
    description: '하굣길 분식집, 떡볶이를 기다리며 거울에 나란히 비친 둘. "어? 너 또 컸냐?" 지훈이 까치발을 들었다가 들킨다.\n"우리 초등 땐 내가 더 컸는데." 말끝이 키 얘기에서 슬쩍 샌다.',
    speakers: ['jihun'],
    location: 'cafe',
    background: 'snack_bar',
    condition: (s) => { const n = s.npcs.find(x => x.id === 'jihun'); return !!n?.met && n.intimacy >= 55 && s.year === 2; },
    choices: [
      { text: '"까치발 든 거 봤어" 놀린다', effects: { social: 1 }, npcEffects: [{ npcId: 'jihun', intimacyChange: 2 }], message: '"안 들었거든!" 발끈하는 지훈 뒤로 떡볶이가 나온다.', timeCost: 1 },
      { text: '"그르게 ㅋㅋ 너 그땐 진짜 콩만했는데" 같이 추억', effects: { social: 1 }, npcEffects: [{ npcId: 'jihun', intimacyChange: 4 }], message: '"야 그건 좀…" 하면서도 지훈이 옛날 얘기에 신이 난다.', timeCost: 1 },
      { text: '"키가 뭐가 중요해" 툭', effects: { mental: 1 }, npcEffects: [{ npcId: 'jihun', intimacyChange: 2 }], message: '"하긴." 지훈이 거울에서 시선을 떼고 떡볶이를 집는다.', timeCost: 1 },
    ],
  },
  {
    id: 'jihun-relay-baton',
    reach: { npc: 'jihun', tier: 65, year: 2 },
    title: '계주, 흔들린 바통',
    description: '체육대회 계주 마지막 주자 지훈이 바통을 놓쳐 등수를 날렸다. 천막 뒤로 빠진 그를 찾아가자, 평소 같으면 "에이 다음에!" 했을 애가 물통을 꽉 쥔 채 말이 없다.\n"나 사실… 안 괜찮아. 맨날… 괜찮은 척했나 봐, 나."',
    speakers: ['jihun'],
    location: 'gym',
    background: 'gymnasium',
    condition: (s) => { const n = s.npcs.find(x => x.id === 'jihun'); return !!n?.met && n.intimacy >= 65 && s.year === 2 && !s.isVacation; },
    choices: [
      { text: '"안 괜찮아도 돼. 나한테까지 척 안 해도 돼" 받아준다', effects: { mental: 2, social: 1 }, npcEffects: [{ npcId: 'jihun', intimacyChange: 5 }], message: '지훈이 물통을 쥔 손에 힘을 풀었다. "…어." 짧게 답하고 한참 말이 없다.', timeCost: 1, memorySlotDraft: { category: 'growth', importance: 7, toneTag: 'warm', recallText: '물통 쥔 지훈, 처음 안 괜찮다던 날.', npcIds: ['jihun'] } },
      { text: '"야 됐어, 나한테까지 척하지 마 좀" 툭', effects: { social: 2 }, npcEffects: [{ npcId: 'jihun', intimacyChange: 5 }], message: '지훈이 피식, 울 듯 말 듯 웃는다. "…너 앞에선 안 되네." 트랙의 환호가 멀게 들린다.', timeCost: 1, memorySlotDraft: { category: 'growth', importance: 7, toneTag: 'warm', recallText: '"너 앞에선 안 되네" — 툭 던진 말에 울 듯 웃던 지훈.', npcIds: ['jihun'] } },
      { text: '말없이 옆에 앉아 물통을 같이 쥔다', effects: { health: 1 }, npcEffects: [{ npcId: 'jihun', intimacyChange: 4 }], message: '둘이 천막 그늘에 앉아 아무 말도 안 한다. 그게 더 편한 순간이 있다.', timeCost: 1 },
    ],
  },
  {
    id: 'jihun-half-gimbap',
    reach: { npc: 'jihun', tier: 70, year: 3 },
    title: '매점 삼각김밥 반쪽',
    description: '마지막 삼각김밥 하나를 두고 동시에 손을 뻗었다. 지훈은 두말없이 반으로 갈라 큰 쪽을 네게 민다.\n"넌 아침 안 먹었잖아."',
    speakers: ['jihun'],
    location: 'cafe',
    background: 'cafeteria_middle',
    condition: (s) => { const n = s.npcs.find(x => x.id === 'jihun'); return !!n?.met && n.intimacy >= 70 && s.year === 3 && !s.isVacation; },
    choices: [
      { text: '"큰 거 네가 먹어" 도로 민다', effects: { social: 1 }, npcEffects: [{ npcId: 'jihun', intimacyChange: 3 }], message: '"됐어 너 먹어." 삼각김밥을 사이에 두고 옥신각신한다.', timeCost: 1 },
      { text: '"넌 어떻게 내 아침 거른 것까지 알아?"', effects: { mental: 1 }, npcEffects: [{ npcId: 'jihun', intimacyChange: 4 }], message: '"그냥 알지 뭐." 지훈이 별일 아니라는 듯 어깨를 으쓱한다.', timeCost: 1 },
      { text: '군말 없이 받고 다음엔 내가 산다 약속', effects: { social: 1 }, npcEffects: [{ npcId: 'jihun', intimacyChange: 3 }], message: '"콜." 계단에 나란히 앉아 반쪽씩 나눠 먹는다.', timeCost: 1 },
    ],
  },
  {
    id: 'jihun-new-shoes',
    reach: { npc: 'jihun', tier: 76, year: 3 },
    title: '새 운동화의 흙',
    description: '새로 산 운동화를 신고 온 지훈이, 웅덩이를 피하다 결국 흙을 묻히고 만다. "에이…" 평소답지 않게 한참 닦는다.\n"새로 산 거라 괜히 아까워서. 더 깨끗이 신고 싶었나 봐."',
    speakers: ['jihun'],
    location: 'street',
    background: 'school_road_morning',
    condition: (s) => { const n = s.npcs.find(x => x.id === 'jihun'); return !!n?.met && n.intimacy >= 76 && s.year === 3; },
    choices: [
      { text: '"흙 좀 묻으면 어때, 네 신발인데"', effects: { mental: 1 }, npcEffects: [{ npcId: 'jihun', intimacyChange: 4 }], message: '"하긴 그러네." 지훈이 휴지를 구겨 넣고 씩 웃는다.', timeCost: 1 },
      { text: '같이 쭈그려 닦아준다', effects: { health: 1 }, npcEffects: [{ npcId: 'jihun', intimacyChange: 4 }], message: '둘이 쭈그려 운동화 코를 닦는다. "야 됐어 손 더러워져." 하면서도 가만히 둔다.', timeCost: 1 },
      { text: '"그 마음 알아" 짧게', effects: { social: 1 }, npcEffects: [{ npcId: 'jihun', intimacyChange: 3 }], message: '지훈이 잠깐 너를 보더니 "…너는 알 것 같더라." 하고 일어선다.', timeCost: 1 },
    ],
  },
  {
    id: 'jihun-six-years-photos',
    reach: { npc: 'jihun', tier: 82, year: 3 },
    title: '6년치 사진',
    description: '사물함 정리 중 지훈의 폴더에서 초등 때부터의 사진들이 우르르 쏟아진다. 운동회, 분식집, 별거 아닌 컷들.\n"버릴 게 없더라. 죄다 우리 같이 찍은 거라서."',
    femaleDescription: '사물함 정리 중 지훈의 폴더에서 초등 때부터의 사진들이 우르르 쏟아진다. 운동회, 분식집, 별거 아닌 컷들.\n"버릴 게 없더라. 죄다 너 나온 거라서."',
    speakers: ['jihun'],
    location: 'hallway',
    background: 'locker_hallway',
    condition: (s) => { const n = s.npcs.find(x => x.id === 'jihun'); return !!n?.met && n.intimacy >= 82 && s.year === 3 && !s.isVacation; },
    choices: [
      { text: '"이거 다 모아둔 거야?" 뭉클', effects: { mental: 2 }, npcEffects: [{ npcId: 'jihun', intimacyChange: 5 }], message: '"어쩌다 보니 안 버리게 되더라." 지훈이 사진을 주섬주섬 챙긴다.', timeCost: 1, memorySlotDraft: { category: 'discovery', importance: 6, toneTag: 'melancholy', recallText: '사물함서 쏟아진 우리 6년 사진.', npcIds: ['jihun'] } },
      { text: '"나도 너 사진 많아" 맞받는다', effects: { social: 1 }, npcEffects: [{ npcId: 'jihun', intimacyChange: 4 }], message: '"진짜? 나중에 합치자." 둘이 바닥에 앉아 사진을 들여다본다.', timeCost: 1 },
      { text: '"정리하랬더니 추억팔이냐" 놀리며 같이 본다', effects: { social: 1 }, npcEffects: [{ npcId: 'jihun', intimacyChange: 4 }], message: '"시끄러." 그러면서도 한 장 한 장 같이 넘겨본다.', timeCost: 1 },
    ],
    femaleChoices: [
      { text: '"이거 다 모아둔 거야?" 뭉클', effects: { mental: 2 }, npcEffects: [{ npcId: 'jihun', intimacyChange: 5 }], message: '"어쩌다 보니." 지훈이 사진을 주워 담으며 시선을 피한다.', timeCost: 1, memorySlotDraft: { category: 'discovery', importance: 6, toneTag: 'melancholy', recallText: '사물함서 쏟아진 우리 6년 사진.', npcIds: ['jihun'] } },
      { text: '"나도 너 사진 많아" 맞받는다', effects: { social: 1 }, npcEffects: [{ npcId: 'jihun', intimacyChange: 4 }], message: '"진짜? 나중에 합치자." 둘이 바닥에 앉아 사진을 들여다본다.', timeCost: 1 },
      { text: '"정리하랬더니 추억팔이냐" 놀리며 같이 본다', effects: { social: 1 }, npcEffects: [{ npcId: 'jihun', intimacyChange: 4 }], message: '"시끄러." 그러면서도 한 장 한 장 같이 넘겨본다.', timeCost: 1 },
    ],
  },
  {
    id: 'jihun-ramen-bet',
    reach: { npc: 'jihun', tier: 85, year: 4 },
    title: '라면 내기',
    description: '지훈이 컵라면 두 개를 들고 "내기하자, 진 사람이 독서실 끝까지 버티기." 웃으며 던진 농담 끝에\n"나도 슬슬 공부 루틴 잡아야 되는데, 같이 다니면 덜 지루하겠다"가 슬쩍 붙는다.',
    femaleDescription: '지훈이 컵라면 두 개를 들고 "내기하자, 진 사람이 독서실 끝까지 버티기." 웃으며 던진 농담 끝에\n"너 독서실 다닌다며? 그럼 나도 다닐까 봐"가 슬쩍 붙는다.',
    speakers: ['jihun'],
    location: 'cafe',
    background: 'cafeteria_middle',
    condition: (s) => { const n = s.npcs.find(x => x.id === 'jihun'); return !!n?.met && n.intimacy >= 85 && s.year === 4 && !s.isVacation; },
    choices: [
      { text: '"갑자기 웬 독서실?" 콕 집는다', effects: { social: 1 }, npcEffects: [{ npcId: 'jihun', intimacyChange: 4 }], message: '"같이 다니면 좀 버틸 만하잖아." 지훈이 컵라면 뚜껑을 뜯는다.', timeCost: 1 },
      { text: '"내기 콜. 단 둘 다 끝까지"', effects: { mental: 1 }, npcEffects: [{ npcId: 'jihun', intimacyChange: 3 }], message: '"콜!" 익어가는 컵라면을 보며 둘이 웃는다.', timeCost: 1 },
      { text: '"네 페이스 지키면서 같이 가자"', effects: { social: 1 }, npcEffects: [{ npcId: 'jihun', intimacyChange: 3 }], message: '"…그래 그게 낫겠다." 지훈이 고개를 끄덕인다.', timeCost: 1 },
    ],
    femaleChoices: [
      { text: '"너 나 따라 독서실 등록하려는 거지?" 콕 집는다', effects: { social: 1 }, npcEffects: [{ npcId: 'jihun', intimacyChange: 4 }], message: '"아 들켰네." 지훈이 컵라면 뚜껑을 만지작거린다.', timeCost: 1 },
      { text: '"내기 콜. 단 둘 다 끝까지"', effects: { mental: 1 }, npcEffects: [{ npcId: 'jihun', intimacyChange: 3 }], message: '"콜!" 익어가는 컵라면을 보며 둘이 웃는다.', timeCost: 1 },
      { text: '"네 페이스 지키면서 같이 가자"', effects: { social: 1 }, npcEffects: [{ npcId: 'jihun', intimacyChange: 3 }], message: '"…그래 그게 낫겠다." 지훈이 고개를 끄덕인다.', timeCost: 1 },
    ],
  },
  {
    id: 'jihun-same-sunset',
    reach: { npc: 'jihun', tier: 88, year: 4 },
    title: '같은 노을',
    description: '노을이 길게 깔린 하굣길, 버스를 기다리며 지훈이 툭 던진다.\n"우리 초딩 때부터 붙어다녔는데, 이렇게 같이 걷는 것도 얼마 안 남았겠다, 그치?"',
    speakers: ['jihun'],
    location: 'street',
    background: 'sunset_walk',
    condition: (s) => { const n = s.npcs.find(x => x.id === 'jihun'); return !!n?.met && n.intimacy >= 88 && s.year === 4; },
    choices: [
      { text: '"앞으로도 쭉 하면 되지" 가볍게', effects: { social: 1 }, npcEffects: [{ npcId: 'jihun', intimacyChange: 4 }], message: '"그래야지." 지훈이 노을 쪽으로 눈을 가늘게 뜬다.', timeCost: 1 },
      { text: '"남은 거 다 같이 보내자" 진지하게', effects: { mental: 1 }, npcEffects: [{ npcId: 'jihun', intimacyChange: 4 }], message: '"…너 갑자기 왜 멋있냐." 지훈이 어색하게 웃는다.', timeCost: 1 },
      { text: '말없이 어깨를 툭 친다', effects: { health: 1 }, npcEffects: [{ npcId: 'jihun', intimacyChange: 3 }], message: '"뭐야 인마." 지훈이 픽 웃는다. 두 그림자가 길게 나란하다.', timeCost: 1 },
    ],
    femaleChoices: [
      { text: '"앞으로도 쭉 하면 되지" 가볍게', effects: { social: 1 }, npcEffects: [{ npcId: 'jihun', intimacyChange: 4 }], message: '"그래야지." 지훈이 노을 쪽으로 눈을 가늘게 뜬다.', timeCost: 1 },
      { text: '"남은 거 다 같이 보내자" 진지하게', effects: { mental: 1 }, npcEffects: [{ npcId: 'jihun', intimacyChange: 4 }], message: '"…너 갑자기 왜 멋있냐." 지훈이 어색하게 웃는다.', timeCost: 1 },
      { text: '말없이 어깨를 툭 기댄다', effects: { health: 1 }, npcEffects: [{ npcId: 'jihun', intimacyChange: 3 }], message: '지훈이 잠깐 멈칫하더니 그대로 둔다. 두 그림자가 길게 나란하다.', timeCost: 1 },
    ],
  },
  {
    id: 'jihun-different-path',
    reach: { npc: 'jihun', tier: 90, year: 4 },
    title: '처음, 안 같이 갈 수도',
    description: '지원서 얘기 끝에 지훈이 멈춰 선다. "야… 우리 어쩌면 처음으로 다른 학교 갈 수도 있겠다."\n농담도 안 붙는다. "맨날 같이 다니다 갈라진다니, 그림이 좀 안 그려지네."',
    femaleDescription: '지원서 얘기 끝에 지훈이 멈춰 선다. "야… 우리 어쩌면 처음으로 다른 학교 갈 수도 있겠다."\n농담도 안 붙는다. "너랑 안 같은 게 어떤 건지 상상이 안 돼."',
    speakers: ['jihun'],
    location: 'hallway',
    background: 'faculty_hallway',
    condition: (s) => { const n = s.npcs.find(x => x.id === 'jihun'); return !!n?.met && n.intimacy >= 90 && s.year === 4 && !s.isVacation; },
    choices: [
      { text: '"어디 가든 너 지훈인 거 안 변해" 단단하게', effects: { mental: 2 }, npcEffects: [{ npcId: 'jihun', intimacyChange: 5 }], message: '지훈이 창밖을 보다 천천히 고개를 끄덕인다. "…그건 그러네."', timeCost: 1, memorySlotDraft: { category: 'growth', importance: 7, toneTag: 'resolve', recallText: '처음 다른 길을 입에 올린 복도.', npcIds: ['jihun'] } },
      { text: '"몰라, 근데 학교 갈린다고 우리가 갈리냐 그게"', effects: { social: 1 }, npcEffects: [{ npcId: 'jihun', intimacyChange: 5 }], message: '"…야 너 말 그렇게 하니까 좀 안심된다." 지훈이 픽 웃는다.', timeCost: 1, memorySlotDraft: { category: 'growth', importance: 7, toneTag: 'resolve', recallText: '처음 다른 길을 입에 올린 복도.', npcIds: ['jihun'] } },
      { text: '"솔직히 나도 무섭다" 같이 인정', effects: { social: 1, mental: 1 }, npcEffects: [{ npcId: 'jihun', intimacyChange: 4 }], message: '"…너도?" 둘이 복도에 서서 한참 창밖만 본다.', timeCost: 1, memorySlotDraft: { category: 'growth', importance: 7, toneTag: 'resolve', recallText: '처음 다른 길을 입에 올린 복도.', npcIds: ['jihun'] } },
    ],
  },

  // ===================== 수빈 (subin) — 외향 뒤 곁다리 =====================
  {
    id: 'subin-cafeteria-line',
    reach: { npc: 'subin', tier: 70, year: 2 },
    title: '매점 줄, 길을 트는 애',
    description: '점심 종 직후 북적이는 매점 줄. 수빈이 곳곳에 인사를 던지며 길을 트고, 쭈뼛대는 너를 자연스럽게 자기 앞으로 끌어다 끼워준다.\n"이런 건 내가 좀 하지." 분위기를 휘어잡는 게 진짜로 즐거워 보인다.',
    speakers: ['subin'],
    location: 'cafe',
    background: 'cafeteria_middle',
    condition: (s) => { const n = s.npcs.find(x => x.id === 'subin'); return !!n?.met && n.intimacy >= 70 && s.year === 2 && !s.isVacation; },
    choices: [
      { text: '"넌 진짜 어디서든 분위기 메이커다" 감탄', effects: { social: 1 }, npcEffects: [{ npcId: 'subin', intimacyChange: 3 }], message: '"이게 내 특기지." 수빈이 으쓱하며 빵을 골라준다.', timeCost: 1 },
      { text: '"덕분에 살았다, 나 혼자였으면 한참 헤맸어"', effects: { social: 1 }, npcEffects: [{ npcId: 'subin', intimacyChange: 4 }], message: '"별거 아냐~" 수빈이 환하게 웃는다.', timeCost: 1 },
      { text: '"다음엔 같이 일찍 오자" 약속', effects: { mental: 1 }, npcEffects: [{ npcId: 'subin', intimacyChange: 3 }], message: '"좋아, 콜." 둘이 빵을 들고 줄을 빠져나온다.', timeCost: 1 },
    ],
  },
  {
    id: 'subin-hundred-chats',
    reach: { npc: 'subin', tier: 74, year: 2 },
    title: '단톡방 백 명',
    description: '등굣길 정류장, 수빈의 단톡방은 수십 개. 알림이 쉴 새 없이 뜬다. "이 많은 데 다 있는데" 하고 웃다가,\n화면을 쓱 내리며 "근데 나한테 직접 온 톡은 없네" 하고 무심한 척 넘긴다.',
    speakers: ['subin'],
    location: 'street',
    background: 'bus_stop_morning',
    condition: (s) => { const n = s.npcs.find(x => x.id === 'subin'); return !!n?.met && n.intimacy >= 74 && s.year === 2; },
    choices: [
      { text: '"그럼 내가 직접 보낼게" 하고 그 자리에서 톡을 보낸다', effects: { social: 1 }, npcEffects: [{ npcId: 'subin', intimacyChange: 4 }], message: '수빈 폰이 띵, 하고 울린다. "…너 방금 나한테 보낸 거야?" 하고 화면을 본다.', timeCost: 1 },
      { text: '"그 많은 데서 직접 온 톡이 없는 게 더 외롭겠다"', effects: { mental: 1 }, npcEffects: [{ npcId: 'subin', intimacyChange: 3 }], message: '수빈이 잠깐 멈칫한다. "…그러고 보니 진짜 그러네."', timeCost: 1 },
      { text: '같이 알림을 하나씩 끄며 정리해준다', effects: { social: 1 }, npcEffects: [{ npcId: 'subin', intimacyChange: 3 }], message: '둘이 머리를 맞대고 단톡방을 정리한다. 화면이 한결 조용해진다.', timeCost: 1 },
    ],
  },
  {
    id: 'subin-always-photographer',
    reach: { npc: 'subin', tier: 78, year: 2 },
    title: '내가 없는 사진',
    description: '반 단체사진 찍는 날. 시키지도 않았는데 수빈이 먼저 폰을 받아 든다. "내가 찍을게! 다들 붙어봐." 찰칵, 찰칵 — 친구들이 환하게 모인다.\n사진을 넘겨보다 수빈이 잠깐 멈춘다. "…나는 또 한 장도 안 들어갔네." 그러곤 금세 웃는다. "뭐, 내가 찍는 게 편하니까."',
    speakers: ['subin'],
    location: 'classroom',
    background: 'classroom_{school}_afternoon',
    condition: (s) => { const n = s.npcs.find(x => x.id === 'subin'); return !!n?.met && n.intimacy >= 78 && s.year === 2 && !s.isVacation; },
    choices: [
      { text: '"폰 이리 줘. 이번 건 너도 들어가야지." 카메라를 둘 쪽으로 돌린다', effects: { social: 1 }, npcEffects: [{ npcId: 'subin', intimacyChange: 5 }], message: '수빈이 어색하게 프레임 안으로 들어온다. "…나 이런 거 진짜 오랜만이다." 찰칵, 둘이 같이 찍힌 첫 장.', timeCost: 1, memorySlotDraft: { category: 'discovery', importance: 7, toneTag: 'warm', recallText: '늘 찍어주기만 하던 애를, 처음 같이 프레임에 넣은 날.', npcIds: ['subin'] } },
      { text: '"네가 찍은 게 제일 잘 나와. 너 눈 좋잖아"', effects: { social: 1 }, npcEffects: [{ npcId: 'subin', intimacyChange: 4 }], message: '"…그치? 내가 좀 잘 찍긴 하지." 으쓱하지만, 폰을 든 손이 조금 오래 멈춰 있다.', timeCost: 1 },
      { text: '말없이, 다음 사진 땐 수빈을 슬쩍 한가운데로 민다', effects: { mental: 1 }, npcEffects: [{ npcId: 'subin', intimacyChange: 4 }], message: '얼떨결에 가운데 선 수빈이 "야, 나 왜 여기—" 하면서도 안 빠져나간다.', timeCost: 1 },
    ],
  },
  {
    id: 'subin-applause-stage',
    reach: { npc: 'subin', tier: 79, year: 3 },
    title: '박수는 무대한테',
    description: '장기자랑 무대가 끝난 직후 동아리방. 수빈이 사회를 봐서 분위기를 다 만들었다. "잘했어!"라 하자\n수빈은 박수 소리 쪽을 턱짓하며 "에이, 박수는 쟤들 거지 뭐" 하고 툭 흘리며 무대 정리를 시작한다.',
    speakers: ['subin'],
    location: 'classroom',
    background: 'club_room',
    condition: (s) => { const n = s.npcs.find(x => x.id === 'subin'); return !!n?.met && n.intimacy >= 79 && s.year === 3 && !s.isVacation; },
    choices: [
      { text: '"네가 안 깔았으면 그 박수도 없었어"', effects: { social: 1 }, npcEffects: [{ npcId: 'subin', intimacyChange: 3 }], message: '"…그런가." 수빈이 마이크 줄을 감던 손을 잠깐 멈춘다.', timeCost: 1 },
      { text: '"그럼 나는 너한테 칠게" 하고 혼자 박수 친다', effects: { social: 1 }, npcEffects: [{ npcId: 'subin', intimacyChange: 4 }], message: '"야 창피하게!" 하면서 수빈 귀가 빨개진다.', timeCost: 1 },
      { text: '같이 무대 정리를 도우며 "다음엔 너도 한 번 서봐"', effects: { mental: 1 }, npcEffects: [{ npcId: 'subin', intimacyChange: 3 }], message: '"내가? 됐어~" 그러면서도 싫지 않은 표정이다.', timeCost: 1 },
    ],
  },
  {
    id: 'subin-name-or-school',
    reach: { npc: 'subin', tier: 82, year: 3 },
    title: '내 이름보다 학교가 먼저',
    description: '하굣길 시내버스 정류장, 여러 학교 애들이 수빈을 "어, ○○중 걔!" 하고 부른다. 익숙하게 받아주다가,\n버스가 떠난 뒤 "쟤들 내 이름은 모르더라. 맨날 ○○중 걔, 이래" 하고 명찰을 만지작거린다.',
    speakers: ['subin'],
    location: 'street',
    background: 'bus_stop_evening',
    condition: (s) => { const n = s.npcs.find(x => x.id === 'subin'); return !!n?.met && n.intimacy >= 82 && s.year === 3; },
    choices: [
      { text: '"난 네 이름부터 알았는데" 하고 또박또박 부른다', effects: { social: 1 }, npcEffects: [{ npcId: 'subin', intimacyChange: 4 }], message: '수빈이 명찰에서 손을 뗀다. "…너는 그러네."', timeCost: 1 },
      { text: '"그럼 오늘부터 내가 네 이름 자주 불러줄게"', effects: { social: 1 }, npcEffects: [{ npcId: 'subin', intimacyChange: 4 }], message: '"부담스럽게 왜 그래~" 하면서도 웃는다.', timeCost: 1 },
      { text: '"이름 모르는 게 쟤들 손해지" 가볍게 받아친다', effects: { social: 1 }, npcEffects: [{ npcId: 'subin', intimacyChange: 2 }], message: '"하긴, 손해지." 수빈이 피식 웃는다.', timeCost: 1 },
    ],
  },
  {
    id: 'subin-runs-without-me',
    reach: { npc: 'subin', tier: 85, year: 3 },
    title: '내가 없어도 굴러가',
    description: '급식실, 혼자 앉은 수빈 옆 테이블에서 애들이 "어제 진짜 역대급으로 재밌었지" 한다. 수빈이 처음 만든 모임인데 어제 자긴 못 갔다.\n식판 위 수저를 만지작거리며 "…봐, 나 없어도 잘 돌아가네."',
    speakers: ['subin'],
    location: 'cafe',
    background: 'cafeteria_middle',
    condition: (s) => { const n = s.npcs.find(x => x.id === 'subin'); return !!n?.met && n.intimacy >= 85 && s.year === 3 && !s.isVacation; },
    choices: [
      { text: '"걔들끼리 재밌던 거랑, 네가 있을 때 재밌던 건 달라"', effects: { social: 1 }, npcEffects: [{ npcId: 'subin', intimacyChange: 5 }], message: '수빈이 수저를 내려놓고 한참 말이 없다. "…너는 자르지 마."', timeCost: 1, memorySlotDraft: { category: 'discovery', importance: 7, toneTag: 'melancholy', recallText: '나 없어도 굴러간다던 급식실.', npcIds: ['subin'] } },
      { text: '"그 모임 누가 만들었더라? 너 빼곤 시작도 안 됐어"', effects: { social: 1 }, npcEffects: [{ npcId: 'subin', intimacyChange: 5 }], message: '"…그건 그러네." 수빈이 작게, 진짜로 웃는다.', timeCost: 1, memorySlotDraft: { category: 'discovery', importance: 7, toneTag: 'melancholy', recallText: '나 없어도 굴러간다던 급식실.', npcIds: ['subin'] } },
      { text: '"없어도 굴러간다고 없어도 되는 건 아니야. 난 네가 있는 쪽이 좋아"', effects: { mental: 1 }, npcEffects: [{ npcId: 'subin', intimacyChange: 5 }], message: '수빈이 고개를 숙인 채 "…고마워" 하고 작게 말한다.', timeCost: 1, memorySlotDraft: { category: 'discovery', importance: 7, toneTag: 'melancholy', recallText: '나 없어도 굴러간다던 급식실.', npcIds: ['subin'] } },
    ],
  },
  {
    id: 'subin-cant-leave-chat',
    reach: { npc: 'subin', tier: 86, year: 4 },
    title: '못 끄겠는 단톡',
    description: '늦은 밤 하굣길 버스, 둘만 남은 뒷자리. 수빈이 폰을 만지작거린다. 거의 죽은 단톡방인데도 "나가기"를 못 누른다.\n"이거 나가면 진짜 끝인 것 같아서. 안 울려도 그냥 둬."',
    speakers: ['subin'],
    location: 'street',
    background: 'night_bus',
    condition: (s) => { const n = s.npcs.find(x => x.id === 'subin'); return !!n?.met && n.intimacy >= 86 && s.year === 4; },
    choices: [
      { text: '"그 방 안 나가도 돼, 대신 나랑은 직접 이어져 있잖아"', effects: { social: 1 }, npcEffects: [{ npcId: 'subin', intimacyChange: 4 }], message: '수빈이 폰을 무릎에 내려놓는다. "…그건 그렇네."', timeCost: 1 },
      { text: '"끄고 싶으면 끄고, 못 끄겠으면 둬도 돼"', effects: { mental: 1 }, npcEffects: [{ npcId: 'subin', intimacyChange: 4 }], message: '"…너는 안 다그치네." 수빈이 차창에 머리를 기댄다.', timeCost: 1 },
      { text: '"나가는 거 무서우면 내가 옆에서 봐줄게"', effects: { social: 1 }, npcEffects: [{ npcId: 'subin', intimacyChange: 3 }], message: '"…아직은 못 누르겠어." 그래도 손가락 힘이 풀린다.', timeCost: 1 },
    ],
  },
  {
    id: 'subin-mom-namecard',
    reach: { npc: 'subin', tier: 88, year: 4 },
    title: '엄마 명함',
    description: '학원 셔틀 안, 가방에서 명함 한 장이 떨어진다. 황급히 줍다가, 잠깐 망설이고 내민다.\n"우리 엄마 명함. 보험 영업. 엄마가 하루에 백 명씩 웃으면서 인사한대."',
    speakers: ['subin'],
    location: 'street',
    background: 'hagwon_shuttle',
    condition: (s) => { const n = s.npcs.find(x => x.id === 'subin'); return !!n?.met && n.intimacy >= 88 && s.year === 4; },
    choices: [
      { text: '"그럼 네 그 능력, 엄마한테 물려받은 거네. 멋있다"', effects: { social: 1 }, npcEffects: [{ npcId: 'subin', intimacyChange: 5 }], message: '수빈이 명함을 도로 곱게 넣으며 옅게 웃는다.', timeCost: 1 },
      { text: '"백 명한테 웃는 거, 아무나 못 해. 너도 마찬가지야"', effects: { social: 1 }, npcEffects: [{ npcId: 'subin', intimacyChange: 4 }], message: '"…그렇게 생각하니까 좀 낫다." 수빈이 명함을 쓰다듬는다.', timeCost: 1 },
      { text: '"언젠가 네가 괜찮으면 더 얘기해줘"', effects: { mental: 1 }, npcEffects: [{ npcId: 'subin', intimacyChange: 3 }], message: '"…응. 언젠가." 수빈이 고개를 끄덕인다.', timeCost: 1 },
    ],
  },
  {
    id: 'subin-two-of-us-home',
    reach: { npc: 'subin', tier: 90, year: 4 },
    title: '늦은 밤, 둘이 사는 집',
    description: '가로등 켜진 동네 골목, 가방 가득 전단을 든 수빈과 마주친다. 들킨 듯 멈칫하던 수빈이 변명도 없이 담담히 말한다.\n"엄마랑 둘이 살아. 엄마가 밤에도 일하니까, 나도 같이 버는 거야."',
    speakers: ['subin'],
    location: 'street',
    background: 'alley_night',
    condition: (s) => { const n = s.npcs.find(x => x.id === 'subin'); return !!n?.met && n.intimacy >= 90 && s.year === 4; },
    choices: [
      { text: '"말해줘서 고마워. 난 네 편이야"', effects: { social: 2, mental: 1 }, npcEffects: [{ npcId: 'subin', intimacyChange: 5 }], message: '수빈이 전단 가방을 안은 채 고개를 숙인다. "…나 처음으로, 안 겉도는 것 같아."', timeCost: 1, memorySlotDraft: { category: 'growth', importance: 7, toneTag: 'resolve', recallText: '둘이 산다고 처음 말한 밤 골목.', npcIds: ['subin'] } },
      { text: '"그게 왜 부끄러워. 너네 진짜 대단한 건데"', effects: { social: 1 }, npcEffects: [{ npcId: 'subin', intimacyChange: 5 }], message: '"…대단하다는 말은 처음 들어." 수빈이 코를 훌쩍인다.', timeCost: 1, memorySlotDraft: { category: 'growth', importance: 7, toneTag: 'resolve', recallText: '둘이 산다고 처음 말한 밤 골목.', npcIds: ['subin'] } },
      { text: '말없이 전단 가방 한쪽을 같이 들어준다', effects: { health: 1 }, npcEffects: [{ npcId: 'subin', intimacyChange: 5 }], message: '둘이 가로등 아래를 나란히 걷는다. 한참 아무 말이 없다.', timeCost: 1, memorySlotDraft: { category: 'growth', importance: 7, toneTag: 'resolve', recallText: '둘이 산다고 처음 말한 밤 골목.', npcIds: ['subin'] } },
    ],
  },

  // ===================== 민재 (minjae) — 등수=나 =====================
  {
    id: 'minjae-three-minute-math',
    reach: { npc: 'minjae', tier: 50, year: 2 },
    title: '매점 3분의 셈',
    description: '매점 진열대 앞에서 민재가 빵 하나를 들었다 놨다 한다. "아 먹고 싶다. 근데 이거 먹으면 나 졸려서 망해." 결국 무가당 두유만 집는다.\n네가 "쌤이냐"고 놀리자 피식 웃는다.',
    speakers: ['minjae'],
    location: 'cafe',
    background: 'cafeteria_middle',
    condition: (s) => { const n = s.npcs.find(x => x.id === 'minjae'); return !!n?.met && n.intimacy >= 50 && s.year === 2 && !s.isVacation; },
    choices: [
      { text: '"그 빵 내가 사줄게, 졸리면 내가 깨워줄게"', effects: { social: 1 }, npcEffects: [{ npcId: 'minjae', intimacyChange: 3 }], message: '"…됐어." 그러면서도 빵을 흘끔 본다.', timeCost: 1 },
      { text: '"3분 먹는 시간도 못 내?"', effects: { mental: 1 }, npcEffects: [{ npcId: 'minjae', intimacyChange: 2 }], message: '민재가 잠깐 멈칫한다. "…그러게." 두유를 만지작거린다.', timeCost: 1 },
      { text: '말없이 같은 두유를 집어 옆에 선다', effects: { social: 1 }, npcEffects: [{ npcId: 'minjae', intimacyChange: 2 }], message: '둘이 두유를 들고 나란히 선다. 민재가 곁눈으로 너를 본다.', timeCost: 1 },
    ],
  },
  {
    id: 'minjae-locker-timetable',
    reach: { npc: 'minjae', tier: 58, year: 2 },
    title: '사물함 안쪽의 시간표',
    description: '떨어진 자료를 같이 줍다, 민재 사물함 문 안쪽에 붙은 손글씨 시간표가 보인다. 분 단위로 쪼갠 칸 사이, 단 한 칸만 비어 있다.\n"거긴… 그냥 비워둔 거야." 그가 황급히 문을 닫는다.',
    speakers: ['minjae'],
    location: 'hallway',
    background: 'locker_hallway',
    condition: (s) => { const n = s.npcs.find(x => x.id === 'minjae'); return !!n?.met && n.intimacy >= 58 && s.year === 2 && !s.isVacation; },
    choices: [
      { text: '"그 칸, 비워두는 게 제일 잘한 거야"', effects: { mental: 1 }, npcEffects: [{ npcId: 'minjae', intimacyChange: 3 }], message: '민재가 문손잡이를 쥔 채 잠깐 멈춘다. "…그런가."', timeCost: 1 },
      { text: '"그 칸엔 뭐가 들어갈 뻔했어?" 조심스레 묻기', effects: { mental: 1 }, npcEffects: [{ npcId: 'minjae', intimacyChange: 2 }], message: '민재가 잠깐 말을 고른다. "…나도 몰라. 그래서 비워뒀어."', timeCost: 1 },
      { text: '"나도 시간표 칸 하나는 늘 비워둬" 나란히 서기', effects: { social: 1 }, npcEffects: [{ npcId: 'minjae', intimacyChange: 3 }], message: '"…너도?" 민재가 처음으로 문을 다시 살짝 연다.', timeCost: 1 },
    ],
  },
  {
    id: 'minjae-point-one',
    reach: { npc: 'minjae', tier: 66, year: 2 },
    title: '0.1점의 이름',
    description: '중간고사 석차표 앞, 민재가 처음으로 2등이다. 0.1점 차. 다들 "그게 어디냐"는데 민재는 웃지 못한다.\n"2등이면… 나 뭐지. 1등 아닌 나는 그냥 아무것도 아닌 거 같아."',
    speakers: ['minjae'],
    location: 'hallway',
    background: 'faculty_hallway',
    condition: (s) => { const n = s.npcs.find(x => x.id === 'minjae'); return !!n?.met && n.intimacy >= 66 && s.year === 2 && !s.isVacation; },
    choices: [
      { text: '"등수가 너냐? 내가 아는 넌 그런 거 아닌데" 반문', effects: { mental: 2 }, npcEffects: [{ npcId: 'minjae', intimacyChange: 5 }], message: '민재가 석차표에서 눈을 뗀다. "…그렇게 말해주는 사람 처음이야."', timeCost: 1, memorySlotDraft: { category: 'discovery', importance: 7, toneTag: 'breakthrough', recallText: '1등 아닌 난 뭐냐 묻던 게시판 앞.', npcIds: ['minjae'] } },
      { text: '"0.1점 때문에 네가 없어지는 건 아니잖아"', effects: { mental: 1, academic: 1 }, npcEffects: [{ npcId: 'minjae', intimacyChange: 3 }], message: '"…머리로는 아는데." 민재가 작게 한숨을 쉰다.', timeCost: 1 },
      { text: '아무 말 없이 옆에 서서 같이 게시판을 본다', effects: { mental: 1 }, npcEffects: [{ npcId: 'minjae', intimacyChange: 4 }], message: '둘이 석차표 앞에 한참 서 있는다. 종소리가 멀게 들린다.', timeCost: 1 },
    ],
  },
  {
    id: 'minjae-dawn-on-hand',
    reach: { npc: 'minjae', tier: 70, year: 3 },
    title: '새벽이 묻은 손등',
    description: '아침 등굣길, 민재가 평소처럼 태연하다. 그런데 단어장을 건네받다 손등에 볼펜으로 빽빽이 적힌 영단어가 보인다. 종이가 모자라 손에까지 적은 새벽.\n"아, 이거… 지워진 줄 알았는데." 소매로 급히 가린다.',
    speakers: ['minjae'],
    location: 'school_gate',
    background: 'school_road_morning',
    condition: (s) => { const n = s.npcs.find(x => x.id === 'minjae'); return !!n?.met && n.intimacy >= 70 && s.year === 3; },
    choices: [
      { text: '"안 지워도 돼. 그거 멋있는데"', effects: { social: 1 }, npcEffects: [{ npcId: 'minjae', intimacyChange: 3 }], message: '"…멋있긴." 그러면서도 소매를 슬쩍 내린다.', timeCost: 1 },
      { text: '"몇 시까지 한 거야 대체" 걱정', effects: { mental: 1 }, npcEffects: [{ npcId: 'minjae', intimacyChange: 2 }], message: '"…기억 안 나." 민재가 얼버무린다.', timeCost: 1 },
      { text: '못 본 척 단어장만 받는다 배려의 외면', effects: { social: 1 }, npcEffects: [{ npcId: 'minjae', intimacyChange: 2 }], message: '민재가 잠깐 너를 본다. 못 본 척해준 걸 안다는 눈빛이다.', timeCost: 1 },
    ],
  },
  {
    id: 'minjae-displayed-model',
    reach: { npc: 'minjae', tier: 76, year: 3 },
    title: '전시된 모범생',
    description: '상담실 밖, 반투명 유리문 너머 새 학부모에게 민재 노트를 펼쳐 보이는 엄마가 보인다. "이게 우리 학원 1등 노트예요—" 영업 멘트인데, 노트를 펼치는 엄마는 무의식중에 살짝 웃고 있다.\n민재는 그것까지 다 본다. "내 노트가 샘플이래. …근데 엄마는 자랑인 줄 아는 것 같아서, 화도 안 나."',
    speakers: ['minjae'],
    location: 'hallway',
    background: 'counseling_hallway',
    condition: (s) => { const n = s.npcs.find(x => x.id === 'minjae'); return !!n?.met && n.intimacy >= 76 && s.year === 3 && !s.isVacation; },
    choices: [
      { text: '"네 노트는 네 거야. 샘플 아니고"', effects: { mental: 1 }, npcEffects: [{ npcId: 'minjae', intimacyChange: 3 }], message: '"…내 거." 민재가 작게 그 말을 따라 한다.', timeCost: 1 },
      { text: '"여기 말고 다른 데 가서 기다리자" 그 자리에서 빼내기', effects: { social: 1 }, npcEffects: [{ npcId: 'minjae', intimacyChange: 4 }], message: '민재가 순순히 일어선다. 복도를 빠져나오자 숨이 조금 트인다.', timeCost: 1 },
      { text: '"샘플치고는 글씨가 너무 너 같은데"', effects: { mental: 1 }, npcEffects: [{ npcId: 'minjae', intimacyChange: 2 }], message: '"…뭐야 그게." 민재가 피식 웃는다.', timeCost: 1 },
    ],
  },
  {
    id: 'minjae-stolen-five-minutes',
    reach: { npc: 'minjae', tier: 82, year: 3 },
    title: '셔틀이 떠난 5분',
    description: '해 질 녘, 민재가 학원 셔틀을 일부러 그냥 보낸다. "한 대만… 한 대만 보낼게." 정류장 천막 아래에서 5분, 처음으로 아무것도 안 한다.\n"엄마한텐 차 놓쳤다고 할 거야."',
    speakers: ['minjae'],
    location: 'street',
    background: 'hagwon_front',
    condition: (s) => { const n = s.npcs.find(x => x.id === 'minjae'); return !!n?.met && n.intimacy >= 82 && s.year === 3; },
    choices: [
      { text: '"그럼 같이 한 대 더 보내자"', effects: { mental: 2 }, npcEffects: [{ npcId: 'minjae', intimacyChange: 5 }], message: '민재가 처음으로 어깨를 푼다. "…그래도 돼?"', timeCost: 1, memorySlotDraft: { category: 'growth', importance: 7, toneTag: 'resolve', recallText: '셔틀 보내고 훔친 5분의 해질녘.', npcIds: ['minjae'] } },
      { text: '"막차 올 때까진 여기 있어도 돼"', effects: { mental: 1 }, npcEffects: [{ npcId: 'minjae', intimacyChange: 4 }], message: '"…고마워." 민재가 천막 기둥에 등을 기댄다.', timeCost: 1 },
      { text: '"거짓말 들통나면 내 핑계 대"', effects: { social: 1 }, npcEffects: [{ npcId: 'minjae', intimacyChange: 4 }], message: '"…너 의외로 든든하다." 민재가 작게 웃는다.', timeCost: 1 },
    ],
  },
  {
    id: 'minjae-red-pen',
    reach: { npc: 'minjae', tier: 84, year: 4 },
    title: '자습실의 빨간펜',
    description: '야간 자습실, 민재가 모의고사 채점지를 펼친다. 틀린 문제 옆 빨간 색깔별 정리—아빠의 채점 습관 그대로다.\n"아빠가 채점하면 빨간펜이 꼭… 나도 모르게 그렇게 해."',
    speakers: ['minjae'],
    location: 'library',
    background: 'study_room_night',
    condition: (s) => { const n = s.npcs.find(x => x.id === 'minjae'); return !!n?.met && n.intimacy >= 84 && s.year === 4 && !s.isVacation; },
    choices: [
      { text: '"빨간펜 잠깐 뺏을게. 오늘은 채점 안 해"', effects: { mental: 1 }, npcEffects: [{ npcId: 'minjae', intimacyChange: 3 }], message: '민재가 빨간펜을 순순히 내려놓는다. "…손이 허전하네."', timeCost: 1 },
      { text: '"틀린 거 옆에 네 말로 한 줄 써봐, 아빠 말고"', effects: { academic: 1, mental: 1 }, npcEffects: [{ npcId: 'minjae', intimacyChange: 4 }], message: '민재가 연필을 들고 한참 망설이다 한 줄을 적는다.', timeCost: 1 },
      { text: '채점지를 슬쩍 덮고 "잠깐 쉬자"', effects: { mental: 1 }, npcEffects: [{ npcId: 'minjae', intimacyChange: 3 }], message: '"…그럴까." 민재가 펜을 내려놓고 의자에 기댄다.', timeCost: 1 },
    ],
  },
  {
    id: 'minjae-good-on-his-own',
    reach: { npc: 'minjae', tier: 88, year: 4 },
    title: '알아서 잘한다는 말',
    description: '교무실 앞에서 교사인 아빠와 마주친다. 아빠가 동료에게 민재를 가리키며 "얘가 우리 애예요, 알아서 잘해서 손 갈 일이 없어요" 하고 어깨를 툭 치고 지나간다.\n민재는 웃는 낯으로 받지만, 돌아서서 멈춰 선다. "알아서 잘한다는 말… 그게 제일 무서워. 아무도 안 봐주잖아, 그러니까…"',
    speakers: ['minjae'],
    location: 'hallway',
    background: 'faculty_hallway',
    condition: (s) => { const n = s.npcs.find(x => x.id === 'minjae'); return !!n?.met && n.intimacy >= 88 && s.year === 4 && !s.isVacation; },
    choices: [
      { text: '"내 앞에선 못해도 돼. 알아서 안 해도 돼"', effects: { mental: 2 }, npcEffects: [{ npcId: 'minjae', intimacyChange: 5 }], message: '민재가 가방끈을 쥔 손에서 힘을 푼다. "…그 말, 처음 들어."', timeCost: 1, memorySlotDraft: { category: 'discovery', importance: 6, toneTag: 'burden', recallText: '알아서 잘한다는 말이 제일 무섭다던.', npcIds: ['minjae'] } },
      { text: '"안 해도 되는 날, 나랑 그냥 놀자"', effects: { social: 1 }, npcEffects: [{ npcId: 'minjae', intimacyChange: 4 }], message: '"…놀아본 게 언젠지 기억도 안 나." 민재가 옅게 웃는다.', timeCost: 1 },
      { text: '"나도 그 말 무거운 거 알아"', effects: { mental: 1 }, npcEffects: [{ npcId: 'minjae', intimacyChange: 4 }], message: '"…너도 그래?" 민재가 처음으로 너를 똑바로 본다.', timeCost: 1 },
    ],
  },
  {
    id: 'minjae-name-in-blank',
    reach: { npc: 'minjae', tier: 92, year: 4 },
    title: '빈칸에 적은 이름',
    description: '진학 자기소개서 양식 앞, "자신을 한 단어로 표현하시오" 빈칸에서 민재가 오래 멈춘다. 늘 정답을 적던 손이 처음으로 떨린다. 그러다 천천히 자기 이름을 적는다.\n"정답 말고… 그냥 나로 시작해보려고."',
    speakers: ['minjae'],
    location: 'classroom',
    background: 'classroom_middle_afternoon',
    condition: (s) => { const n = s.npcs.find(x => x.id === 'minjae'); return !!n?.met && n.intimacy >= 92 && s.year === 4 && !s.isVacation; },
    choices: [
      { text: '"좋은 답이야. 그게 제일 정답이야"', effects: { mental: 1 }, npcEffects: [{ npcId: 'minjae', intimacyChange: 5 }], message: '민재가 자기 이름을 한참 들여다본다. "…응. 그렇게 생각할래."', timeCost: 1, memorySlotDraft: { category: 'growth', importance: 7, toneTag: 'breakthrough', recallText: '빈칸에 정답 대신 제 이름 적던 날.', npcIds: ['minjae'] } },
      { text: '"진짜 괜찮겠어? 1등 아닌 너로 시작하는 거" 되묻기', effects: { mental: 1, academic: 1 }, npcEffects: [{ npcId: 'minjae', intimacyChange: 4 }], message: '민재가 잠깐 멈칫하더니 천천히 고개를 끄덕인다. "…응. 처음으로 진짜 그러고 싶어."', timeCost: 1, memorySlotDraft: { category: 'growth', importance: 7, toneTag: 'breakthrough', recallText: '빈칸에 정답 대신 제 이름 적던 날.', npcIds: ['minjae'] } },
      { text: '그가 적은 이름 옆에 너도 한 단어를 적어준다', effects: { social: 1 }, npcEffects: [{ npcId: 'minjae', intimacyChange: 5 }], message: '민재가 네가 적은 단어를 보고 처음으로 환하게 웃는다.', timeCost: 1, memorySlotDraft: { category: 'growth', importance: 7, toneTag: 'breakthrough', recallText: '빈칸에 정답 대신 제 이름 적던 날.', npcIds: ['minjae'] } },
    ],
  },

  // ===================== 유나 (yuna) — 피아노 변질→예고 기로→잔류+회복 =====================
  // Y3 전학 소문(transfer-rumor)은 Y4 clearing-locker에서 "예고 안 감(잔류)"으로 명시 해소된다.
  // → 고등 아크(reachHigh yuna-hs-*, npc/yuna.ts yuna-smile)의 "같은 일반고 재학" 전제와 정합.
  {
    id: 'yuna-metronome',
    reach: { npc: 'yuna', tier: 72, year: 2 },
    title: '음악실 메트로놈',
    description: '점심에 잠깐 들른 음악실. 유나가 메트로놈을 빠르게 맞춰놓고 손가락만 까딱이고 있다.\n"곡을 안 쳐도 박자만 맞춰두면 뭔가 한 것 같아서. …나 이거 좋아했었나." 정작 건반엔 손을 안 올린다.',
    speakers: ['yuna'],
    location: 'music_room',
    background: 'music_room_middle',
    condition: (s) => { const n = s.npcs.find(x => x.id === 'yuna'); return !!n?.met && n.intimacy >= 72 && s.year === 2 && !s.isVacation; },
    choices: [
      { text: '"한 곡만 쳐봐, 나 들을게" 권유', effects: { talent: 1 }, npcEffects: [{ npcId: 'yuna', intimacyChange: 2 }], message: '유나가 망설이다 건반에 손을 올린다. 한 소절 치고는 멈춘다.', timeCost: 1 },
      { text: '"메트로놈 끄고 그냥 아무거나 쳐봐" 장난스런 흔듦', effects: { talent: 1 }, npcEffects: [{ npcId: 'yuna', intimacyChange: 3 }], message: '"아무거나?" 유나가 메트로놈을 멈추고 피식 웃는다.', timeCost: 1 },
      { text: '"박자 맞추는 것도 연습이지 뭐"', effects: { mental: 1 }, npcEffects: [{ npcId: 'yuna', intimacyChange: 1 }], message: '"그치?" 유나가 다시 메트로놈을 본다. 손은 여전히 무릎 위다.', timeCost: 1 },
    ],
  },
  {
    id: 'yuna-song-pick',
    reach: { npc: 'yuna', tier: 78, year: 2 },
    title: '동아리방 곡 추천',
    description: '학예제 합주곡을 정하는 자리. 유나가 한참 좋다고 골라온 곡을 들고 와서는, 막판에\n"근데 이거 너무 튀려나? 무난한 걸로 할까" 하고 슬며시 거둬들인다.',
    speakers: ['yuna'],
    location: 'music_room',
    background: 'music_room_middle',
    condition: (s) => { const n = s.npcs.find(x => x.id === 'yuna'); return !!n?.met && n.intimacy >= 78 && s.year === 2 && !s.isVacation; },
    choices: [
      { text: '"네가 좋다는 거 해. 책임은 같이 질게"', effects: { talent: 1, social: 1 }, npcEffects: [{ npcId: 'yuna', intimacyChange: 3 }], message: '"…같이?" 유나가 등 뒤로 숨겼던 악보를 다시 꺼낸다.', timeCost: 1 },
      { text: '"왜 거둬? 방금 눈 반짝였잖아"', effects: { mental: 1 }, npcEffects: [{ npcId: 'yuna', intimacyChange: 2 }], message: '유나가 멈칫한다. "…티 났어?"', timeCost: 1 },
      { text: '"무난한 게 안전하긴 하지" 동조', effects: { mental: 1 }, npcEffects: [{ npcId: 'yuna', intimacyChange: 1 }], message: '"그치. 안전한 게 낫지." 유나가 악보를 접는다. 어딘가 아쉬운 얼굴로.', timeCost: 1 },
    ],
  },
  {
    id: 'yuna-light-booth',
    reach: { npc: 'yuna', tier: 82, year: 2 },
    title: '안 틀려도 되는 자리',
    description: '학예제 당일, 다들 유나가 무대에서 칠 줄 알았는데 조명 담당을 자원했다. 부스 어둠 속에서 슬쩍 흘린다.\n"무대 서면 틀리는 거 다 보이잖아… 여긴 뭐, 안 틀려도 되니까."',
    speakers: ['yuna'],
    location: 'auditorium',
    background: 'auditorium_middle',
    condition: (s) => { const n = s.npcs.find(x => x.id === 'yuna'); return !!n?.met && n.intimacy >= 82 && s.year === 2 && !s.isVacation; },
    choices: [
      { text: '"여기서도 잘 보여. 근데 무대 위 너도 언젠가 보고 싶다"', effects: { talent: 1, mental: 1 }, npcEffects: [{ npcId: 'yuna', intimacyChange: 4 }], message: '유나가 페이더를 만지작거린다. "…언젠가는, 그럴까."', timeCost: 1, memorySlotDraft: { category: 'discovery', importance: 7, toneTag: 'melancholy', recallText: '무대 대신 조명 부스 고른 유나.', npcIds: ['yuna'] } },
      { text: '"틀리면 좀 어때. 나는 안 보는데" 가볍게 풀어주기', effects: { mental: 1 }, npcEffects: [{ npcId: 'yuna', intimacyChange: 3 }], message: '"…너는 그렇게 말하네." 유나가 어둠 속에서 작게 웃는다.', timeCost: 1, memorySlotDraft: { category: 'discovery', importance: 7, toneTag: 'melancholy', recallText: '무대 대신 조명 부스 고른 유나.', npcIds: ['yuna'] } },
      { text: '"왜 뒤로 갔어? 너 무대 좋아했잖아"', effects: { mental: 1 }, npcEffects: [{ npcId: 'yuna', intimacyChange: 3 }], message: '유나가 페이더에 손을 얹은 채 한참 답이 없다. "…좋아했었지."', timeCost: 1, memorySlotDraft: { category: 'discovery', importance: 7, toneTag: 'melancholy', recallText: '무대 대신 조명 부스 고른 유나.', npcIds: ['yuna'] } },
    ],
  },
  {
    id: 'yuna-rank-board',
    reach: { npc: 'yuna', tier: 83, year: 3 },
    title: '성적 게시판 앞, 분한 마음',
    description: '모의고사 등수가 막 게시된 복도 게시판 앞. 한 끗 차이로 유나가 밀렸다. 분해하면서도\n"근데 그게 너라서 좀 덜 분해" 하고 웃는다.',
    speakers: ['yuna'],
    location: 'hallway',
    background: 'hallway_middle',
    condition: (s) => { const n = s.npcs.find(x => x.id === 'yuna'); return !!n?.met && n.intimacy >= 83 && s.year === 3 && !s.isVacation; },
    choices: [
      { text: '"나도 너라서 봐줄 맘 없는데"', effects: { academic: 1 }, npcEffects: [{ npcId: 'yuna', intimacyChange: 3 }], message: '"오, 좋아 그래야 재밌지." 유나 눈이 반짝인다.', timeCost: 1 },
      { text: '"분한 거 인정하네, 너답다"', effects: { mental: 1 }, npcEffects: [{ npcId: 'yuna', intimacyChange: 2 }], message: '"…티 났어?" 유나가 입을 삐죽인다.', timeCost: 1 },
      { text: '"다음엔 안 진다"', effects: { academic: 1 }, npcEffects: [{ npcId: 'yuna', intimacyChange: 2 }], message: '"흥, 어디 해봐." 유나가 웃으며 게시판을 떠난다.', timeCost: 1 },
    ],
  },
  {
    id: 'yuna-teacher-comment',
    reach: { npc: 'yuna', tier: 85, year: 3 },
    title: '교무실 앞 소견문',
    description: '선생님이 써준 소견문을 받아 든 유나가 "열심히 하는 모습이 보기 좋다"는 문장 앞에서 굳는다.\n"나 그냥… 열심히 보이기만 하는 거 아닐까. 진짜로는 별로 안 하는데."',
    speakers: ['yuna'],
    location: 'hallway',
    background: 'faculty_hallway',
    condition: (s) => { const n = s.npcs.find(x => x.id === 'yuna'); return !!n?.met && n.intimacy >= 85 && s.year === 3 && !s.isVacation; },
    choices: [
      { text: '"안 보이는 데서도, 너 너잖아"', effects: { mental: 1 }, npcEffects: [{ npcId: 'yuna', intimacyChange: 3 }], message: '유나가 소견문을 접는다. "…그렇게 말해주니까 좀 낫다."', timeCost: 1 },
      { text: '"그럼 안 보이는 데서 뭐 하는지 나한테만 말해줘"', effects: { social: 1 }, npcEffects: [{ npcId: 'yuna', intimacyChange: 3 }], message: '"…너한테만?" 유나가 잠깐 웃는다.', timeCost: 1 },
      { text: '"그래도 선생님은 네가 애쓴 걸 본 거 아닐까"', effects: { mental: 1 }, npcEffects: [{ npcId: 'yuna', intimacyChange: 2 }], message: '"…그런가." 유나가 소견문을 다시 한 번 읽는다.', timeCost: 1 },
    ],
  },
  {
    id: 'yuna-transfer-rumor',
    reach: { npc: 'yuna', tier: 88, year: 3 },
    title: '전학 소문, 웃지 않음',
    description: '비 오는 날 현관 처마 밑, "유나가 예고로 전학 간대, 피아노로 승부 본다더라"는 소문이 돈다. 사실이냐 묻자, 유나가 처음으로 웃지 않는다.\n"응. 갈지도 몰라." 그 침묵이 한참 빗소리를 머금는다.',
    speakers: ['yuna'],
    location: 'school_gate',
    // 본문이 '현관 처마 밑' — 기존 school_gate_{school}_rain 에셋이 정확히 맞음 (Y3→middle).
    // school_entrance_rain 키는 siwoo-demolished-ground(철거 골목 빗속) 전용으로 재지정 (2026-07-20 배경 발주 검수).
    background: 'school_gate_{school}_rain',
    condition: (s) => { const n = s.npcs.find(x => x.id === 'yuna'); return !!n?.met && n.intimacy >= 88 && s.year === 3 && !s.isVacation; },
    choices: [
      { text: '"안 웃어도 돼. 지금은."', effects: { mental: 2 }, npcEffects: [{ npcId: 'yuna', intimacyChange: 4 }], message: '유나가 빗줄기를 본다. "…고마워. 안 웃어도 된다는 말." ', timeCost: 1, memorySlotDraft: { category: 'discovery', importance: 7, toneTag: 'melancholy', recallText: '전학 소문에 처음 안 웃던 처마 밑.', npcIds: ['yuna'] } },
      { text: '"가든 안 가든, 네 피아노 들으러 갈게"', effects: { talent: 1 }, npcEffects: [{ npcId: 'yuna', intimacyChange: 4 }], message: '"…진짜 올 거야?" 유나가 처음으로 눈을 마주친다.', timeCost: 1, memorySlotDraft: { category: 'discovery', importance: 7, toneTag: 'melancholy', recallText: '전학 소문에 처음 안 웃던 처마 밑.', npcIds: ['yuna'] } },
      { text: '"안 갔으면 좋겠다, 솔직히" 붙잡음', effects: { social: 1 }, npcEffects: [{ npcId: 'yuna', intimacyChange: 3 }], message: '유나가 잠깐 말이 없다. "…나도." 빗소리만 가득하다.', timeCost: 1, memorySlotDraft: { category: 'discovery', importance: 7, toneTag: 'melancholy', recallText: '전학 소문에 처음 안 웃던 처마 밑.', npcIds: ['yuna'] } },
    ],
  },
  {
    id: 'yuna-wet-score',
    reach: { npc: 'yuna', tier: 86, year: 4 },
    title: '젖은 악보',
    description: '오후, 가방 속 물통이 새서 젖은 악보를 유나가 라디에이터에 한 장씩 말리고 있다. 예전 같으면 발 동동 굴렀을 텐데,\n"어차피 마르면 또 쳐. 서두른다고 빨리 안 말라." 조급함이 한 칸 빠진 모습.',
    speakers: ['yuna'],
    location: 'music_room',
    background: 'music_room_middle',
    condition: (s) => { const n = s.npcs.find(x => x.id === 'yuna'); return !!n?.met && n.intimacy >= 86 && s.year === 4 && !s.isVacation; },
    choices: [
      { text: '"너 좀 변했다, 좋은 쪽으로"', effects: { mental: 1 }, npcEffects: [{ npcId: 'yuna', intimacyChange: 3 }], message: '"그런가?" 유나가 악보를 톡톡 만지며 웃는다.', timeCost: 1 },
      { text: '"같이 말리자, 빨리 안 마르는 거 옆에서 봐줄게"', effects: { social: 1 }, npcEffects: [{ npcId: 'yuna', intimacyChange: 3 }], message: '둘이 라디에이터 앞에 쪼그려 악보를 넌다. 조용한 오후다.', timeCost: 1 },
      { text: '"예전 너였으면 난리 났을 텐데" 놀림', effects: { mental: 1 }, npcEffects: [{ npcId: 'yuna', intimacyChange: 2 }], message: '"맞아, 옛날 같았으면." 유나가 머쓱하게 웃는다.', timeCost: 1 },
    ],
  },
  {
    id: 'yuna-clearing-locker',
    reach: { npc: 'yuna', tier: 89, year: 4 },
    title: '사물함 정리',
    description: '2학기 중반. 유나가 사물함에서 예고 입시 자료를 하나씩 꺼내 종이가방에 담고 있다. 요강, 콩쿠르 안내문, 연습 계획표.\n"…나 예고는 안 가기로 했어. 원서, 안 냈어." 담담한데 어딘가 후련한 얼굴이다.',
    speakers: ['yuna'],
    location: 'hallway',
    background: 'locker_hallway',
    condition: (s) => { const n = s.npcs.find(x => x.id === 'yuna'); return !!n?.met && n.intimacy >= 89 && s.year === 4 && !s.isVacation; },
    choices: [
      { text: '"잘 생각했어. 네 속도로 가"', effects: { social: 1 }, npcEffects: [{ npcId: 'yuna', intimacyChange: 4 }], message: '유나가 요강을 종이가방에 마저 넣는다. "…네가 그렇게 말해주니까, 진짜 괜찮은 것 같다."', timeCost: 1 },
      { text: '"후회 안 하겠어?"', effects: { mental: 1 }, npcEffects: [{ npcId: 'yuna', intimacyChange: 2 }], message: '"…모르지. 근데 지금은 이게 맞아." 유나 손이 잠깐 멈춘다.', timeCost: 1 },
      { text: '"그 상장은 버리지 마, 네가 잘한 거잖아"', effects: { talent: 1 }, npcEffects: [{ npcId: 'yuna', intimacyChange: 3 }], message: '유나가 상장을 다시 종이가방에 넣는다. "…이건 안 버릴게. 예고를 안 갈 뿐이지, 피아노를 놓는 건 아니니까."', timeCost: 1 },
    ],
  },
  {
    id: 'yuna-last-recital',
    reach: { npc: 'yuna', tier: 92, year: 4 },
    title: '등수 없는 곡',
    description: '유나가 빈 음악실에서 "콩쿠르 곡 말고, 그냥 좋아하는 곡 한 번만 쳐도 돼?" 하고 묻는다. 예고도, 등수도 내려놓은 자리. 평가 없는 연주가 끝나고\n"아 맞다… 나 이거 좋아했었네."',
    speakers: ['yuna'],
    location: 'music_room',
    background: 'music_room_middle',
    condition: (s) => { const n = s.npcs.find(x => x.id === 'yuna'); return !!n?.met && n.intimacy >= 92 && s.year === 4 && !s.isVacation; },
    choices: [
      { text: '"지금 그 표정, 처음 봐. 진짜 같애."', effects: { talent: 1, mental: 1 }, npcEffects: [{ npcId: 'yuna', intimacyChange: 5 }], message: '유나가 건반에서 손을 떼고 환하게 웃는다. 처음으로, 역할 없이.', timeCost: 1, memorySlotDraft: { category: 'reconciliation', importance: 7, toneTag: 'warm', recallText: '등수 내려놓은 곡에서, 좋아함을 되찾은 유나.', npcIds: ['yuna'] } },
      { text: '"이제 그 표정으로 계속 치면 되겠다"', effects: { social: 1 }, npcEffects: [{ npcId: 'yuna', intimacyChange: 5 }], message: '"…응. 등수 말고, 이런 걸로." 유나가 고개를 끄덕인다.', timeCost: 1, memorySlotDraft: { category: 'reconciliation', importance: 7, toneTag: 'warm', recallText: '등수 내려놓은 곡에서, 좋아함을 되찾은 유나.', npcIds: ['yuna'] } },
      { text: '"한 곡만 더. 듣고 싶어서."', effects: { mental: 1 }, npcEffects: [{ npcId: 'yuna', intimacyChange: 4 }], message: '"…좋아. 딱 한 곡만 더." 유나가 다시 건반에 손을 올린다.', timeCost: 1, memorySlotDraft: { category: 'reconciliation', importance: 7, toneTag: 'warm', recallText: '등수 내려놓은 곡에서, 좋아함을 되찾은 유나.', npcIds: ['yuna'] } },
    ],
  },

  // ===================== 하은 (haeun) — 챙기는 여자 선배(1년 위) =====================
  {
    id: 'haeun-lost-and-found',
    reach: { npc: 'haeun', tier: 30, year: 2 },
    title: '분실물함의 체육복',
    description: '체육복을 잃어버려 분실물함을 뒤지는 후배 옆에, 선배 하은이 같이 쪼그려 앉아 함께 뒤져준다.\n"여기 자주 와. 중학교 오면 다들 한 번씩 뭐 잃어버리더라."',
    speakers: ['haeun'],
    location: 'hallway',
    background: 'hallway_middle',
    condition: (s) => { const n = s.npcs.find(x => x.id === 'haeun'); return !!n?.met && n.intimacy >= 30 && s.year === 2 && !s.isVacation; },
    choices: [
      { text: '"어… 선배도 그런 거 잃어버려요?" 천진하게', effects: { social: 1 }, npcEffects: [{ npcId: 'haeun', intimacyChange: 2 }], message: '"나? 나도 작년에 두 번 잃어봤지." 하은이 웃으며 옷더미를 뒤진다.', timeCost: 1 },
      { text: '같이 묵묵히 뒤진다', effects: { mental: 1 }, npcEffects: [{ npcId: 'haeun', intimacyChange: 3 }], message: '둘이 말없이 옷더미를 뒤진다. "찾았다." 하은이 체육복을 건넨다.', timeCost: 1 },
      { text: '"자주 와봤나 봐요" 슬쩍 떠보기', effects: { mental: 1 }, npcEffects: [{ npcId: 'haeun', intimacyChange: 1 }], message: '"…그러게." 하은이 한쪽 입꼬리만 올리고 웃는다.', timeCost: 1 },
    ],
  },
  {
    id: 'haeun-handover-note',
    reach: { npc: 'haeun', tier: 42, year: 2 },
    title: '인수인계 노트',
    description: '졸업 선배에게서 물려받은 동아리방. 하은이 후배를 위해 미리 적어둔 빼곡한 인수인계 노트를 건넨다.\n자기 이름 칸 옆엔 "←여기까지가 내가 한 거, 담부턴 헷갈리지 말고"라고 작게 끄적여져 있다.',
    speakers: ['haeun'],
    location: 'classroom',
    background: 'club_room',
    condition: (s) => { const n = s.npcs.find(x => x.id === 'haeun'); return !!n?.met && n.intimacy >= 42 && s.year === 2 && !s.isVacation; },
    choices: [
      { text: '"이걸 다 적었어요?"', effects: { social: 1 }, npcEffects: [{ npcId: 'haeun', intimacyChange: 3 }], message: '"후배가 헤매면 안 되잖아." 하은이 당연하다는 듯 말한다.', timeCost: 1 },
      { text: '"여기까지가 내 거, 라니… 뭔가 미리 정리하는 것 같아요"', effects: { mental: 1 }, npcEffects: [{ npcId: 'haeun', intimacyChange: 2 }], message: '"…그런가? 그냥 헷갈리지 말라고." 하은이 노트를 톡톡 친다.', timeCost: 1 },
      { text: '"선배 거 칸은 비었네요"', effects: { mental: 1 }, npcEffects: [{ npcId: 'haeun', intimacyChange: 2 }], message: '"…내 칸은 뭐, 별거 없으니까." 하은이 팔짱을 낀다.', timeCost: 1 },
    ],
  },
  {
    id: 'haeun-broadcast-mic',
    reach: { npc: 'haeun', tier: 55, year: 2 },
    title: '방송실 마이크',
    description: '하은이 점심방송 진행을 맡았다. ON AIR 직전 손끝이 미세하게 떨리는 걸 후배만 본다. 방송이 끝나고\n"떨려도 끝까지 읽으면, 그게 방송이 되더라"라고 한다.',
    speakers: ['haeun'],
    location: 'classroom',
    background: 'broadcast_room',
    condition: (s) => { const n = s.npcs.find(x => x.id === 'haeun'); return !!n?.met && n.intimacy >= 55 && s.year === 2 && !s.isVacation; },
    choices: [
      { text: '"선배도 떨려요?" 의외라는 듯', effects: { social: 1 }, npcEffects: [{ npcId: 'haeun', intimacyChange: 4 }], message: '"안 떠는 게 아니라, 떨면서 끝까지 가는 거야." 하은이 마이크를 정리한다.', timeCost: 1, memorySlotDraft: { category: 'growth', importance: 7, toneTag: 'warm', recallText: '떨려도 끝까지 읽으면 방송이 된다던.', npcIds: ['haeun'] } },
      { text: '"끝까지 잘 들었어요"', effects: { social: 1 }, npcEffects: [{ npcId: 'haeun', intimacyChange: 5 }], message: '"…고마워. 듣는 사람 있으니까 끝까지 했네." 하은이 옅게 웃는다.', timeCost: 1, memorySlotDraft: { category: 'growth', importance: 7, toneTag: 'warm', recallText: '떨려도 끝까지 읽으면 방송이 된다던.', npcIds: ['haeun'] } },
      { text: '"손 떨던 거 봤어요" 조용히 본 걸 말해주기', effects: { mental: 1 }, npcEffects: [{ npcId: 'haeun', intimacyChange: 3 }], message: '하은이 잠깐 멈칫한다. "…그것도 봤구나." 그 떨림을, 나만 봤다.', timeCost: 1, memorySlotDraft: { category: 'growth', importance: 7, toneTag: 'warm', recallText: '떨려도 끝까지 읽으면 방송이 된다던.', npcIds: ['haeun'] } },
    ],
  },
  {
    id: 'haeun-brothers-book',
    reach: { npc: 'haeun', tier: 62, year: 3 },
    title: '오빠 참고서',
    description: '하은이 참고서를 펼치며 "이거 이 선배가 물려받은 비기야~ 후배 너도 보여줄까?" 하고 으스댄다.\n그러다 표지 안쪽 다른 이름—오빠 이름—에서 손가락이 멈추고, 으스대던 웃음이 슬며시 옅어진다.',
    speakers: ['haeun'],
    location: 'cafe',
    background: 'school_bench',
    condition: (s) => { const n = s.npcs.find(x => x.id === 'haeun'); return !!n?.met && n.intimacy >= 62 && s.year === 3; },
    choices: [
      { text: '"오빠는 지금 뭐 해요?" 가볍게 묻기', effects: { social: 1 }, npcEffects: [{ npcId: 'haeun', intimacyChange: 2 }], message: '"…뭐, 그냥 지내." 하은이 표지를 덮는다.', timeCost: 1 },
      { text: '"선배는 다를 거예요"', effects: { mental: 1 }, npcEffects: [{ npcId: 'haeun', intimacyChange: 3 }], message: '"…그럴까." 하은이 참고서를 가방에 넣는다.', timeCost: 1 },
      { text: '"…그 표정, 무슨 일 있어요?"', effects: { mental: 1 }, npcEffects: [{ npcId: 'haeun', intimacyChange: 2 }], message: '"아무것도. …아니다." 하은이 말을 삼킨다.', timeCost: 1 },
    ],
  },
  {
    id: 'haeun-highlighter-overdraw',
    reach: { npc: 'haeun', tier: 72, year: 3 },
    title: '자습실의 덧칠',
    description: '야간 자습실, 하은이 고등 입시자료를 펼친다. 형광펜으로 같은 한 줄만 몇 번이고 덧긋는다. 종이가 일어날 만큼.\n후배가 다가오자 자료를 탁 덮으며 "별거 아냐, 미리 보는 거"라고 한다.',
    speakers: ['haeun'],
    location: 'library',
    background: 'study_room_night',
    condition: (s) => { const n = s.npcs.find(x => x.id === 'haeun'); return !!n?.met && n.intimacy >= 72 && s.year === 3 && !s.isVacation; },
    choices: [
      { text: '"제가 옆에 있을게요" 말없이 자리 지키기', effects: { mental: 2 }, npcEffects: [{ npcId: 'haeun', intimacyChange: 4 }], message: '하은이 형광펜을 내려놓는다. "…그래 줄래?"', timeCost: 1 },
      { text: '"미리 보면 덜 무서워요?" 조심스레 묻기', effects: { mental: 1 }, npcEffects: [{ npcId: 'haeun', intimacyChange: 3 }], message: '"…아니. 봐도 무서워." 하은이 작게 답한다.', timeCost: 1 },
      { text: '"선배도 무서운 거 있구나" 솔직하게 짚기', effects: { social: 2 }, npcEffects: [{ npcId: 'haeun', intimacyChange: 3 }], message: '하은이 자료를 덮은 손을 가만히 둔다. "…너한테 들켰네."', timeCost: 1 },
    ],
  },
  {
    id: 'haeun-before-application',
    reach: { npc: 'haeun', tier: 80, year: 3 },
    title: '원서 앞에서',
    description: '고등 원서 마감 직전, 교무실 앞 복도에서 하은이 원서를 든 채 서 있다. 후배를 보자 선배 역할을 처음으로 내려놓고 털어놓는다.\n"오빠가 그때 원하는 데 썼다가, 많이 힘들어졌거든. 난… 안전한 데 써야 하나. 무서워."',
    speakers: ['haeun'],
    location: 'hallway',
    background: 'faculty_hallway',
    condition: (s) => { const n = s.npcs.find(x => x.id === 'haeun'); return !!n?.met && n.intimacy >= 80 && s.year === 3 && !s.isVacation; },
    choices: [
      { text: '"선배가 원하는 데 써요"', effects: { social: 1 }, npcEffects: [{ npcId: 'haeun', intimacyChange: 5 }], message: '"…그래도 될까." 하은이 원서를 꼭 쥔다.', timeCost: 1, memorySlotDraft: { category: 'courage', importance: 7, toneTag: 'breakthrough', recallText: '원서 앞, 선배가 처음 무섭다던 날.', npcIds: ['haeun'] } },
      { text: '"안전한 게 나쁜 건 아니에요"', effects: { mental: 1 }, npcEffects: [{ npcId: 'haeun', intimacyChange: 4 }], message: '"…그 말도 위로가 되네." 하은이 옅게 웃는다.', timeCost: 1, memorySlotDraft: { category: 'courage', importance: 7, toneTag: 'breakthrough', recallText: '원서 앞, 선배가 처음 무섭다던 날.', npcIds: ['haeun'] } },
      { text: '"선배도 그냥 무서울 수 있어요"', effects: { mental: 2 }, npcEffects: [{ npcId: 'haeun', intimacyChange: 5 }], message: '하은이 처음으로 후배 앞에서 어깨를 늘어뜨린다. "…응. 나 사실 무서워."', timeCost: 1, memorySlotDraft: { category: 'courage', importance: 7, toneTag: 'breakthrough', recallText: '원서 앞, 선배가 처음 무섭다던 날.', npcIds: ['haeun'] } },
    ],
  },
] satisfies readonly GameEvent[];
