import { GameEvent } from '../types';

// ===== 고교(Y5~Y7) 친밀도 도달형 이벤트 =====
// docs/reach-high-brief.md 설계. 중학교(reachMid)에 대응하는 고교 사다리.
// week 없음 + condition 게이트(intimacy>=tier && year===Y)로 reach 풀 진입. 페이싱 엔진(getReachForWeek)이
// fresh 즉시 / pre-met 쿨다운 분산 처리. 교내 장면은 !s.isVacation 가드.
// 고교 톤 = 수렴: 새 만남보다 진로·갈림길·이별·졸업. 깊어지는 게 아니라 *끝을 향해 같이 걷는* 결.
// importance: 진입5/중간6/핵심7. memorySlotDraft는 핵심 컷(학년당 1개꼴)에만. recallText 20~35자.

export const HIGH_REACH_EVENTS = [
  // ===================== 지훈 (jihun) — 소꿉친구·활기=방패 / 입시가 둘의 시간을 가른다 =====================
  // Wave 1. Y4 "6년치 사진"(82)에서 이어, 말 못한 거리감 → 각자의 길 → 졸업의 아크.
  // ---- Y5 (고1): 갈라지는 시간표 ----
  {
    id: 'jihun-hs-timetable',
    reach: { npc: 'jihun', tier: 80, year: 5 },
    title: '다른 반',
    description: '고교 첫 반배정. 6년 만에 처음으로 지훈과 다른 반이 됐다. 쉬는 시간, 복도 끝에서 지훈이 손을 흔들며 온다.\n"이제 너 보려면 복도 끝까지 와야 되네. 운동 삼아 온다 생각해야지 뭐." 웃는데 숨이 조금 차 있다.',
    femaleDescription: '고교 첫 반배정. 6년 만에 처음으로 지훈과 다른 반이 됐다. 쉬는 시간, 복도 끝에서 지훈이 손을 흔들며 온다.\n"이제 너 보려면 복도 끝까지 와야 되네." 매 쉬는 시간 굳이 여기까지 온다는 건, 끝에 가서야 알게 된다.',
    speakers: ['jihun'],
    location: 'hallway',
    background: 'classroom_high',
    condition: (s) => { const n = s.npcs.find(x => x.id === 'jihun'); return !!n?.met && n.intimacy >= 80 && s.year === 5 && !s.isVacation; },
    choices: [
      { text: '"매번 오기 힘들면 안 와도 돼" 툭', effects: { mental: 1 }, npcEffects: [{ npcId: 'jihun', intimacyChange: 3 }], message: '"안 오면 또 섭섭해할 거면서." 지훈이 픽 웃으며 벽에 기댄다.', timeCost: 1 },
      { text: '"그럼 다음 쉬는 시간엔 내가 갈게"', effects: { social: 1 }, npcEffects: [{ npcId: 'jihun', intimacyChange: 4 }], message: '"오 그래. 그럼 번갈아 가면 되겠네." 지훈이 손가락을 튕긴다.', timeCost: 1 },
      { text: '"반 갈린 거 좀 어색하다, 그치"', effects: { mental: 1 }, npcEffects: [{ npcId: 'jihun', intimacyChange: 4 }], message: '"…어. 이렇게 반 갈린 건 처음이잖아." 지훈이 잠깐 복도 끝을 본다.', timeCost: 1 },
    ],
    femaleChoices: [
      { text: '"매번 오기 힘들면 안 와도 돼" 툭', effects: { mental: 1 }, npcEffects: [{ npcId: 'jihun', intimacyChange: 3 }], message: '"…그래도 와야 얼굴 보지." 지훈이 귀를 만지며 딴 데를 본다.', timeCost: 1 },
      { text: '"그럼 다음 쉬는 시간엔 내가 갈게"', effects: { social: 1 }, npcEffects: [{ npcId: 'jihun', intimacyChange: 4 }], message: '"오 그래. 그럼 번갈아 가면 되겠네." 지훈이 손가락을 튕긴다.', timeCost: 1 },
      { text: '"반 갈린 거 좀 어색하다, 그치"', effects: { mental: 1 }, npcEffects: [{ npcId: 'jihun', intimacyChange: 4 }], message: '"…어. 이렇게 반 갈린 건 처음이잖아." 지훈이 잠깐 복도 끝을 본다.', timeCost: 1 },
    ],
  },
  {
    id: 'jihun-hs-latenight',
    reach: { npc: 'jihun', tier: 85, year: 5 },
    title: '야자 끝 버스',
    description: '야간자율학습이 끝난 밤. 같은 버스를 탔는데, 6년 동안 한 번도 없던 일이 벌어진다 — 할 말이 없다.\n지훈이 창밖만 본다. 평소 같으면 벌써 열 마디는 했을 애가, 가방끈만 만지작거린다. 어색한 침묵이 정류장 두 개를 지난다.',
    femaleDescription: '야간자율학습이 끝난 밤. 같은 버스를 탔는데, 6년 동안 한 번도 없던 일이 벌어진다 — 할 말이 없다.\n지훈이 창밖만 본다. 어깨가 닿을 듯한 거리인데, 둘 다 그걸 의식하느라 더 말이 없다. 침묵이 정류장 두 개를 지난다.',
    speakers: ['jihun'],
    location: 'street',
    background: 'night_bus',
    condition: (s) => { const n = s.npcs.find(x => x.id === 'jihun'); return !!n?.met && n.intimacy >= 85 && s.year === 5; },
    choices: [
      { text: '"우리 언제부터 할 말 없었지?" 먼저 깬다', effects: { mental: 2 }, npcEffects: [{ npcId: 'jihun', intimacyChange: 5 }], message: '"…그르게." 지훈이 픽 웃는다. "근데 이 침묵도 너랑이라 편하긴 하다." 버스가 흔들린다.', timeCost: 1, memorySlotDraft: { category: 'growth', importance: 6, toneTag: 'melancholy', recallText: '야자 끝 버스, 6년 만에 처음 어색하던 침묵.', npcIds: ['jihun'] } },
      { text: '말없이 이어폰 한쪽을 건넨다', effects: { health: 1, mental: 1 }, npcEffects: [{ npcId: 'jihun', intimacyChange: 5 }], message: '지훈이 이어폰을 받아 낀다. 노래 한 곡이 흐르는 동안, 말이 없어도 괜찮아진다.', timeCost: 1, memorySlotDraft: { category: 'growth', importance: 6, toneTag: 'warm', recallText: '말 없던 밤 버스, 나눠 낀 이어폰 한쪽.', npcIds: ['jihun'] } },
      { text: '"피곤하지" 짧게 묻고 같이 창밖을 본다', effects: { mental: 1 }, npcEffects: [{ npcId: 'jihun', intimacyChange: 4 }], message: '"어. 너도." 짧은 대답 뒤로 둘이 같은 어둠을 본다.', timeCost: 1 },
    ],
    femaleChoices: [
      { text: '"우리 언제부터 할 말 없었지?" 먼저 깬다', effects: { mental: 2 }, npcEffects: [{ npcId: 'jihun', intimacyChange: 5 }], message: '"…몰라. 근데 너랑은 이 침묵도 안 불편해." 지훈이 창에 비친 너를 슬쩍 본다.', timeCost: 1, memorySlotDraft: { category: 'growth', importance: 6, toneTag: 'melancholy', recallText: '야자 끝 버스, 6년 만에 처음 어색하던 침묵.', npcIds: ['jihun'] } },
      { text: '말없이 이어폰 한쪽을 건넨다', effects: { health: 1, mental: 1 }, npcEffects: [{ npcId: 'jihun', intimacyChange: 5 }], message: '지훈이 이어폰을 받아 낀다. 어깨가 한 뼘 가까워진 채로, 노래 한 곡이 흐른다.', timeCost: 1, memorySlotDraft: { category: 'growth', importance: 6, toneTag: 'warm', recallText: '말 없던 밤 버스, 나눠 낀 이어폰 한쪽.', npcIds: ['jihun'] } },
      { text: '"피곤하지" 짧게 묻고 같이 창밖을 본다', effects: { mental: 1 }, npcEffects: [{ npcId: 'jihun', intimacyChange: 4 }], message: '"어. 너도." 짧은 대답 뒤로 둘이 같은 어둠을 본다.', timeCost: 1 },
    ],
  },
  {
    id: 'jihun-hs-firstgap',
    reach: { npc: 'jihun', tier: 89, year: 5 },
    title: '처음 깜빡한 약속',
    description: '방과후에 만나기로 한 날, 지훈이 안 나타난다. 한참 뒤 도착한 메시지. "미안 학원 보강 완전 까먹고 있었어."\n다음 날 지훈이 머리를 긁적인다. "나 진짜 너랑 약속 깜빡한 거 처음이지? 요즘 정신이 없어서, 진짜 미안."',
    speakers: ['jihun'],
    location: 'street',
    background: 'bus_stop_evening',
    condition: (s) => { const n = s.npcs.find(x => x.id === 'jihun'); return !!n?.met && n.intimacy >= 89 && s.year === 5; },
    choices: [
      { text: '"괜찮아, 너도 바쁜 거 아는데 뭐"', effects: { mental: 1 }, npcEffects: [{ npcId: 'jihun', intimacyChange: 4 }], message: '"그래도 너한텐 안 그러고 싶었는데." 지훈이 입맛을 다신다.', timeCost: 1 },
      { text: '"한 번은 봐준다. 대신 떡볶이 사" 가볍게', effects: { social: 1 }, npcEffects: [{ npcId: 'jihun', intimacyChange: 4 }], message: '"콜. 곱빼기로." 지훈이 그제야 평소 얼굴로 웃는다.', timeCost: 1 },
      { text: '"우리도 이제 서로 바빠지나 보다" 툭', effects: { mental: 1 }, npcEffects: [{ npcId: 'jihun', intimacyChange: 3 }], message: '"…그 말이 더 따끔하네." 지훈이 뒷머리를 긁는다.', timeCost: 1 },
    ],
  },
  // ---- Y6 (고2): 각자의 길이 보이기 시작 ----
  {
    id: 'jihun-hs-track',
    reach: { npc: 'jihun', tier: 90, year: 6 },
    title: '갈림길',
    description: '문이과·진로가 갈리는 시기. 지훈은 체대 준비를 굳혔다. 진학실 앞 게시판을 같이 보다가 지훈이 툭 던진다.\n"우리 이제 진짜 다른 데 가는구나. 야, 도윤이 걔도 어디 멀리 갔다더라." 말끝을 흐린다. 평소답지 않게 게시판 앞을 안 뜬다.',
    speakers: ['jihun'],
    location: 'hallway',
    background: 'counseling_hallway',
    condition: (s) => { const n = s.npcs.find(x => x.id === 'jihun'); return !!n?.met && n.intimacy >= 90 && s.year === 6 && !s.isVacation; },
    choices: [
      { text: '"다른 데 가도 우린 우리잖아"', effects: { mental: 1, social: 1 }, npcEffects: [{ npcId: 'jihun', intimacyChange: 5 }], message: '"…그건 그래." 지훈이 게시판으로 다시 시선을 돌린다. 픽, 짧게만 웃는다.', timeCost: 1 },
      { text: '"체대 가면 너 진짜 멋있겠다" 진심으로', effects: { social: 1 }, npcEffects: [{ npcId: 'jihun', intimacyChange: 4 }], message: '"그치? 나도 그렇게 생각해." 지훈이 어깨를 펴 보인다. 그 허세가 반갑다.', timeCost: 1 },
      { text: '"갈라지는 거 생각하면 좀 그렇다" 솔직히', effects: { mental: 1 }, npcEffects: [{ npcId: 'jihun', intimacyChange: 4 }], message: '"…나도. 근데 어쩌겠어, 가야지." 지훈이 게시판의 한 줄을 괜히 손끝으로 짚는다.', timeCost: 1 },
    ],
    femaleChoices: [
      { text: '"다른 데 가도 우린 우리잖아"', effects: { mental: 1, social: 1 }, npcEffects: [{ npcId: 'jihun', intimacyChange: 5 }], message: '"…그건 그래." 지훈이 게시판에서 시선을 안 떼고 답한다. "근데 좀 이상하긴 하다. 너랑 안 같은 칸인 게."', timeCost: 1 },
      { text: '"체대 가면 너 진짜 멋있겠다" 진심으로', effects: { social: 1 }, npcEffects: [{ npcId: 'jihun', intimacyChange: 4 }], message: '"그치?" 으스대다 말고 지훈이 슬쩍 본다. "…너 가는 데는, 여기서 멀어?"', timeCost: 1 },
      { text: '"갈라지는 거 생각하면 좀 그렇다" 솔직히', effects: { mental: 1 }, npcEffects: [{ npcId: 'jihun', intimacyChange: 4 }], message: '"…나도." 지훈이 게시판 대신 너를 한 번 보고, 도로 게시판으로 눈을 돌린다.', timeCost: 1 },
    ],
  },
  {
    id: 'jihun-hs-unsaid',
    reach: { npc: 'jihun', tier: 93, year: 6 },
    title: '말 못한 한마디',
    description: '야자 빠진 저녁, 둘만 남은 교실. 노을이 책상 줄을 길게 가른다. 지훈이 한참 말이 없다가, 입을 열려다 만다.\n"…아니다." 평소의 활기가 없다. "야, 나 사실 너한테 할 말이 있는데." 그러고는 또 멈춘다. 무언가가 목에 걸린 얼굴이다.',
    femaleDescription: '야자 빠진 저녁, 둘만 남은 교실. 노을이 책상 줄을 길게 가른다. 지훈이 한참 말이 없다가, 입을 열려다 만다.\n"…아니다." 평소의 활기가 없다. "야, 나 사실 너한테…" 그러고는 또 멈춘다. 귀가 조금 붉다. 무언가가 목에 걸린 얼굴이다.',
    speakers: ['jihun'],
    location: 'classroom',
    background: 'classroom_high_afternoon',
    condition: (s) => { const n = s.npcs.find(x => x.id === 'jihun'); return !!n?.met && n.intimacy >= 93 && s.year === 6 && !s.isVacation; },
    choices: [
      { text: '"천천히 말해. 나 안 가고 기다릴게" 끝까지 듣는다', effects: { mental: 2, social: 1 }, npcEffects: [{ npcId: 'jihun', intimacyChange: 5 }], message: '지훈이 숨을 한 번 고른다. "…야, 너 없었으면 고등학교 어떻게 버텼냐. 그 말, 한 번은 해야 될 것 같아서." 노을이 둘 사이로 진다.', timeCost: 1, memorySlotDraft: { category: 'growth', importance: 7, toneTag: 'breakthrough', recallText: '둘만 남은 교실, 지훈이 끝내 꺼낸 한마디.', npcIds: ['jihun'] } },
      { text: '"말하기 힘들면 안 해도 돼" 퇴로를 연다', effects: { mental: 1, social: 1 }, npcEffects: [{ npcId: 'jihun', intimacyChange: 4 }], message: '"…그래. 다음에 하지 뭐." 지훈이 그 말을 도로 삼킨다. 무언가가 노을 속으로 그냥 묻힌다.', timeCost: 1, memorySlotDraft: { category: 'failure', importance: 7, toneTag: 'regret', recallText: '둘만 남은 교실, 지훈이 끝내 못 꺼낸 한마디.', npcIds: ['jihun'] } },
      { text: '"긴장한 너 처음 본다" 분위기를 푼다', effects: { social: 1 }, npcEffects: [{ npcId: 'jihun', intimacyChange: 3 }], message: '"긴장은 무슨!" 발끈하는 사이 타이밍이 지나간다. 지훈이 그 말을 도로 삼킨다.', timeCost: 1, memorySlotDraft: { category: 'failure', importance: 7, toneTag: 'regret', recallText: '둘만 남은 교실, 지훈이 끝내 못 꺼낸 한마디.', npcIds: ['jihun'] } },
    ],
    femaleChoices: [
      { text: '"천천히 말해. 나 안 가고 기다릴게" 끝까지 듣는다', effects: { mental: 2, social: 1 }, npcEffects: [{ npcId: 'jihun', intimacyChange: 6 }], message: '지훈이 숨을 한 번 고른다. "…너 없는 학교는 상상이 안 돼. 그 말, 하고 싶었어." 귀가 더 붉어진 채로, 시선은 안 피한다.', timeCost: 1, memorySlotDraft: { category: 'growth', importance: 7, toneTag: 'breakthrough', recallText: '둘만 남은 교실, 지훈이 끝내 꺼낸 한마디.', npcIds: ['jihun'] } },
      { text: '"말하기 힘들면 안 해도 돼" 퇴로를 연다', effects: { mental: 1, social: 1 }, npcEffects: [{ npcId: 'jihun', intimacyChange: 4 }], message: '"…아니야, 됐다." 지훈이 웃어넘긴다. "다음에." 다음이라는 말이 노을 속으로 묻힌다.', timeCost: 1, memorySlotDraft: { category: 'failure', importance: 7, toneTag: 'regret', recallText: '둘만 남은 교실, 지훈이 끝내 못 꺼낸 한마디.', npcIds: ['jihun'] } },
      { text: '"긴장한 너 처음 본다" 분위기를 푼다', effects: { social: 1 }, npcEffects: [{ npcId: 'jihun', intimacyChange: 3 }], message: '"긴장은 무슨!" 발끈하는 사이 타이밍이 지나간다. 지훈이 그 말을 도로 삼킨다.', timeCost: 1, memorySlotDraft: { category: 'failure', importance: 7, toneTag: 'regret', recallText: '둘만 남은 교실, 지훈이 끝내 못 꺼낸 한마디.', npcIds: ['jihun'] } },
    ],
  },
  {
    id: 'jihun-hs-injury',
    reach: { npc: 'jihun', tier: 95, year: 6 },
    title: '다친 날',
    description: '체대 입시 연습 중 지훈이 발목을 크게 접질렸다는 소식. 수업도 제치고 달려가니, 보건실 침대에 앉은 지훈이 너를 보고 멈칫한다.\n"…너 수업은? 야, 그렇다고 진짜 오냐." 핀잔 같은 말인데, 표정이 풀린다. "역시 너밖에 없네."',
    femaleDescription: '체대 입시 연습 중 지훈이 발목을 크게 접질렸다는 소식. 수업도 제치고 달려가니, 보건실 침대에 앉은 지훈이 너를 보고 멈칫한다.\n"…너 수업은? 야, 그렇다고 진짜 오냐." 핀잔 같은 말인데, 안도한 얼굴을 숨기지 못한다. "역시 너밖에 없네."',
    speakers: ['jihun'],
    location: 'classroom',
    // 본문이 '보건실 침대' — school_bench(교정 벤치)와 불일치. infirmary는 신규 발주 에셋
    // (docs/cg-prompts-backgrounds-2026-07.md). 생성 전까지는 location(classroom) 폴백으로 동작.
    background: 'infirmary',
    condition: (s) => { const n = s.npcs.find(x => x.id === 'jihun'); return !!n?.met && n.intimacy >= 95 && s.year === 6 && !s.isVacation; },
    choices: [
      { text: '"당연히 오지. 많이 아파?" 발목부터 살핀다', effects: { mental: 1, health: 1 }, npcEffects: [{ npcId: 'jihun', intimacyChange: 5 }], message: '"엄살은 아닌데… 좀 아파." 늘 괜찮다던 녀석이, 발목 대신 너를 한 번 본다.', timeCost: 1 },
      { text: '"입시 앞두고 이러면 어떡해" 화부터 난다', effects: { mental: 1 }, npcEffects: [{ npcId: 'jihun', intimacyChange: 5 }], message: '"…너 지금 걱정하는 거지." 지훈이 픽 웃는다. "알아, 화내는 게 더 걱정인 거."', timeCost: 1 },
      { text: '말없이 옆에 앉아 가방에서 음료를 꺼내준다', effects: { health: 1 }, npcEffects: [{ npcId: 'jihun', intimacyChange: 4 }], message: '지훈이 음료를 받아 쥔다. "…고맙다." 보건실 커튼 사이로 오후 볕이 든다.', timeCost: 1 },
    ],
    femaleChoices: [
      { text: '"당연히 오지. 많이 아파?" 발목부터 살핀다', effects: { mental: 1, health: 1 }, npcEffects: [{ npcId: 'jihun', intimacyChange: 5 }], message: '"…네가 옆에 있으니까 좀 낫네." 말해놓고 지훈이 괜히 천장을 본다.', timeCost: 1 },
      { text: '"입시 앞두고 이러면 어떡해" 화부터 난다', effects: { mental: 1 }, npcEffects: [{ npcId: 'jihun', intimacyChange: 5 }], message: '"…너 지금 걱정하는 거지." 지훈이 픽 웃는다. "알아, 화내는 게 더 걱정인 거."', timeCost: 1 },
      { text: '말없이 옆에 앉아 가방에서 음료를 꺼내준다', effects: { health: 1 }, npcEffects: [{ npcId: 'jihun', intimacyChange: 4 }], message: '지훈이 음료를 받아 쥔다. "…너 진짜." 말끝을 못 맺고, 커튼 사이 볕만 본다.', timeCost: 1 },
    ],
  },
  // ---- Y7 (고3): 마지막 함께 ----
  {
    id: 'jihun-hs-lastgame',
    reach: { npc: 'jihun', tier: 96, year: 7 },
    title: '마지막 경기',
    description: '지훈의 고교 마지막 시합. 관중석은 듬성듬성한데, 지훈이 코트에 들어서며 딱 한 번 스탠드를 훑는다. 그 시선이 너에게서 멈춘다.\n경기 내내 안 보는 척하면서도, 좋은 플레이가 나올 때마다 네 쪽을 한 번씩 본다.',
    speakers: ['jihun'],
    location: 'gym',
    background: 'gymnasium',
    condition: (s) => { const n = s.npcs.find(x => x.id === 'jihun'); return !!n?.met && n.intimacy >= 96 && s.year === 7 && !s.isVacation; },
    choices: [
      { text: '경기 내내 제일 큰 소리로 응원한다', effects: { social: 1, health: 1 }, npcEffects: [{ npcId: 'jihun', intimacyChange: 5 }], message: '경기 끝, 땀범벅 지훈이 스탠드로 와 씩 웃는다. "네 목소리만 들리더라. 시끄러워서 더 잘했잖아, 인마."', timeCost: 1 },
      { text: '"끝나고 떡볶이 쏜다" 손으로 신호 보낸다', effects: { social: 1 }, npcEffects: [{ npcId: 'jihun', intimacyChange: 4 }], message: '지훈이 코트에서 엄지를 들어 보인다. 응원석에서 여기까지, 그 한 번이 다 닿는다.', timeCost: 1 },
      { text: '말없이 끝까지 자리를 지킨다', effects: { mental: 1 }, npcEffects: [{ npcId: 'jihun', intimacyChange: 4 }], message: '마지막 호루라기. 지훈이 거친 숨을 고르며 너 있는 쪽을 오래 본다. "…와줄 줄 알았어."', timeCost: 1 },
    ],
    femaleChoices: [
      { text: '경기 내내 제일 큰 소리로 응원한다', effects: { social: 1, health: 1 }, npcEffects: [{ npcId: 'jihun', intimacyChange: 5 }], message: '경기 끝, 땀범벅 지훈이 곧장 스탠드로 온다. "딴 응원은 안 들리고 네 목소리만 들리더라." 숨이 찬 채로 픽 웃는다.', timeCost: 1 },
      { text: '"끝나고 떡볶이 쏜다" 손으로 신호 보낸다', effects: { social: 1 }, npcEffects: [{ npcId: 'jihun', intimacyChange: 4 }], message: '지훈이 코트에서 엄지를 들어 보인다. 그러곤 다른 데 안 보고, 네 쪽만 한 번 더 본다.', timeCost: 1 },
      { text: '말없이 끝까지 자리를 지킨다', effects: { mental: 1 }, npcEffects: [{ npcId: 'jihun', intimacyChange: 4 }], message: '마지막 호루라기. 지훈이 거친 숨을 고르며 너 있는 쪽을 오래 본다. "…끝까지 네가 있더라."', timeCost: 1 },
    ],
  },
  {
    id: 'jihun-hs-graduation',
    reach: { npc: 'jihun', tier: 97, year: 7 },
    title: '같은 사진 한 장 더',
    description: '졸업식. 식이 끝나고 운동장 구석, 지훈이 핸드폰을 내민다. "야, 마지막으로 한 장." 화면엔 초등 운동회 때 둘이 찍은 빛바랜 사진이 띄워져 있다.\n"6년치 사진이라더니, 이젠 12년치네." 지훈이 화면 속 낡은 운동회 사진을 엄지로 한 번 문지른다. "한 장만 더 넣자." 그 사물함 속 폴더가, 긴 시간을 건너 여기까지 왔다.',
    femaleDescription: '졸업식. 식이 끝나고 운동장 구석, 지훈이 핸드폰을 내민다. "야, 마지막으로 한 장." 화면엔 초등 운동회 때 둘이 찍은 빛바랜 사진이 띄워져 있다.\n"6년치 사진이라더니, 이젠 12년치네." 지훈이 화면 속 옛 사진을 엄지로 문지르다, 괜히 한마디 덧붙인다. "…앞으로도 네 사진이 제일 많긴 하겠다."',
    speakers: ['jihun'],
    location: 'auditorium',
    background: 'auditorium_high',
    condition: (s) => { const n = s.npcs.find(x => x.id === 'jihun'); return !!n?.met && n.intimacy >= 97 && s.year === 7; },
    choices: [
      { text: '"12년치 사진, 한 장도 안 버릴게"', effects: { mental: 2 }, npcEffects: [{ npcId: 'jihun', intimacyChange: 6 }], message: '"…나도." 지훈이 사진을 찍는다. 찰칵. "이게 첫 장이다, 다음 12년." 둘이 같은 화면을 들여다본다.', timeCost: 1, memorySlotDraft: { category: 'reconciliation', importance: 7, toneTag: 'warm', recallText: '졸업식, 6년치 사진에 더한 마지막 한 장.', npcIds: ['jihun'] } },
      { text: '"다음 12년도 같이 찍자" 약속한다', effects: { mental: 2, social: 1 }, npcEffects: [{ npcId: 'jihun', intimacyChange: 6 }], message: '"콜. 약속이다, 인마." 지훈이 새끼손가락을 내민다. 졸업생 행렬 소리가 멀게 들린다.', timeCost: 1, memorySlotDraft: { category: 'reconciliation', importance: 7, toneTag: 'warm', recallText: '졸업식, 6년치 사진에 더한 마지막 한 장.', npcIds: ['jihun'] } },
      { text: '"우리 진짜 다 컸다, 그치" 사진을 같이 본다', effects: { mental: 1 }, npcEffects: [{ npcId: 'jihun', intimacyChange: 5 }], message: '"그르게. 콩만 하던 게." 지훈이 옛 사진 속 자기 키를 보며 웃는다. 그 웃음이 12년 전과 똑같다.', timeCost: 1, memorySlotDraft: { category: 'reconciliation', importance: 7, toneTag: 'warm', recallText: '졸업식, 6년치 사진에 더한 마지막 한 장.', npcIds: ['jihun'] } },
    ],
    femaleChoices: [
      { text: '"앞으로 찍을 사진도 다 너랑이면 좋겠어"', effects: { mental: 2 }, npcEffects: [{ npcId: 'jihun', intimacyChange: 6 }], message: '지훈이 잠깐 말을 잃는다. "…야, 그건 반칙이지." 귀가 빨개진 채로 사진을 찍는다. 찰칵.', timeCost: 1, memorySlotDraft: { category: 'reconciliation', importance: 7, toneTag: 'warm', recallText: '졸업식, 6년치 사진에 더한 마지막 한 장.', npcIds: ['jihun'] } },
      { text: '"다음 12년도 같이 찍자" 약속한다', effects: { mental: 2, social: 1 }, npcEffects: [{ npcId: 'jihun', intimacyChange: 6 }], message: '"콜. 약속이다." 지훈이 새끼손가락을 내민다. 평소보다 한참 오래 걸어둔다.', timeCost: 1, memorySlotDraft: { category: 'reconciliation', importance: 7, toneTag: 'warm', recallText: '졸업식, 6년치 사진에 더한 마지막 한 장.', npcIds: ['jihun'] } },
      { text: '"우리 진짜 다 컸다, 그치" 사진을 같이 본다', effects: { mental: 1 }, npcEffects: [{ npcId: 'jihun', intimacyChange: 5 }], message: '"그르게. 콩만 하던 게." 지훈이 옛 사진 속 자기 키를 보며 웃는다. 그 웃음이 12년 전과 똑같다.', timeCost: 1, memorySlotDraft: { category: 'reconciliation', importance: 7, toneTag: 'warm', recallText: '졸업식, 6년치 사진에 더한 마지막 한 장.', npcIds: ['jihun'] } },
    ],
  },
  // ===================== 수빈 (subin) — 밝음 뒤 소속 갈증 / 승무원 꿈 =====================
  // 기존 캡스톤 dream(Y5,≥60)·farewell(Y7,≥70)으로 수렴하는 리드인 사다리.
  {
    id: 'subin-hs-firstdream',
    reach: { npc: 'subin', tier: 55, year: 5 },
    title: '비행기 사진',
    description: '쉬는 시간, 수빈 핸드폰이 울린다. 잠금화면이 뜬 순간 — 이륙하는 비행기 사진이다. 늘 친구들 단체사진이던 그 화면에.\n"어? 아 이거." 수빈이 멋쩍게 화면을 끈다. "그냥… 보면 좀 시원해서. 어디든 갈 수 있을 것 같고."',
    speakers: ['subin'],
    location: 'classroom',
    background: 'classroom_high',
    condition: (s) => { const n = s.npcs.find(x => x.id === 'subin'); return !!n?.met && n.intimacy >= 55 && s.year === 5 && !s.isVacation; },
    choices: [
      { text: '"승무원 같은 거 생각해?" 짚는다', effects: { social: 1 }, npcEffects: [{ npcId: 'subin', intimacyChange: 5 }], message: '"…티 났어?" 수빈이 웃는데, 남들한테 하던 그 웃음이 아니다. "아직 아무한테도 말 안 했는데."', timeCost: 1 },
      { text: '"너랑 잘 어울린다, 그 꿈"', effects: { mental: 1 }, npcEffects: [{ npcId: 'subin', intimacyChange: 5 }], message: '"그래?" 수빈이 잠금화면을 다시 켜본다. "…네가 처음이야. 어울린다고 해준 거."', timeCost: 1 },
      { text: '"어디 가고 싶은데?" 같이 본다', effects: { social: 1 }, npcEffects: [{ npcId: 'subin', intimacyChange: 4 }], message: '수빈이 신나서 가본 적도 없는 도시 이름들을 줄줄 댄다. 그 순간만은 남 눈치를 안 본다.', timeCost: 1 },
    ],
  },
  {
    id: 'subin-hs-momfight',
    reach: { npc: 'subin', tier: 64, year: 6 },
    title: '엄마와 부딪힌 날',
    description: '방과후 빈 교실, 수빈이 엄마랑 통화하다 끊는다. 늘 웃던 얼굴이 굳어 있다.\n"엄마는… 승무원 말고 안정적인 거 하래. 공무원 같은 거." 책상에 엎드린다. "나 처음으로 엄마한테 대들었어." 어깨가 작게 흔들린다.',
    speakers: ['subin'],
    location: 'classroom',
    background: 'classroom_high_afternoon',
    condition: (s) => { const n = s.npcs.find(x => x.id === 'subin'); return !!n?.met && n.intimacy >= 64 && s.year === 6 && !s.isVacation; },
    choices: [
      { text: '말없이 옆에 앉아 등을 토닥인다', effects: { mental: 1, health: 1 }, npcEffects: [{ npcId: 'subin', intimacyChange: 6 }], message: '수빈이 엎드린 채 한참 있는다. "…남들 앞에선 우는 거 한 번도 안 했는데." 너한테만 운다.', timeCost: 1, memorySlotDraft: { category: 'growth', importance: 6, toneTag: 'melancholy', recallText: '빈 교실, 남들 앞에선 안 울던 애가 운 날.', npcIds: ['subin'] } },
      { text: '"엄마도 너 걱정돼서 그러는 거야"', effects: { mental: 1 }, npcEffects: [{ npcId: 'subin', intimacyChange: 4 }], message: '"알아. 아는데…" 수빈이 고개를 못 든다. "아는 게 더 힘들어." 맞는 말이 위로가 안 되는 순간.', timeCost: 1 },
      { text: '"그 꿈, 내가 응원할게. 한 명은 있어야지"', effects: { social: 1 }, npcEffects: [{ npcId: 'subin', intimacyChange: 6 }], message: '수빈이 고개를 든다. 눈이 빨갛다. "…한 명. 그래, 한 명이면 되는데." 처음으로 응원이란 걸 받아본 얼굴.', timeCost: 1 },
    ],
  },
  {
    id: 'subin-hs-studyboard',
    reach: { npc: 'subin', tier: 68, year: 6 },
    title: '영어 단어장',
    description: '스터디카페 구석, 수빈이 영어 단어장을 혼자 중얼거린다. "승무원 면접은 영어가 된대서." 평소 공부랑 안 친하던 애가, 발음을 몇 번씩 고쳐 읽는다.\n"근데 혼자 하니까 자꾸 까먹어. …같이 외워줄 사람도 없고."',
    speakers: ['subin'],
    location: 'cafe',
    background: 'cafe_study',
    condition: (s) => { const n = s.npcs.find(x => x.id === 'subin'); return !!n?.met && n.intimacy >= 68 && s.year === 6 && !s.isVacation; },
    choices: [
      { text: '"내가 같이 외워줄게" 옆에 앉는다', effects: { social: 1 }, npcEffects: [{ npcId: 'subin', intimacyChange: 6 }], message: '"진짜?" 수빈이 단어장을 반으로 펼쳐 네 쪽으로 민다. "…이런 거 같이 하자고 한 거, 네가 처음이야."', timeCost: 1 },
      { text: '"발음 좋은데? 잘하고 있어"', effects: { mental: 1 }, npcEffects: [{ npcId: 'subin', intimacyChange: 5 }], message: '"에이." 그러면서도 수빈이 더 또박또박 읽는다. 누가 들어준다는 것만으로.', timeCost: 1 },
      { text: '단어 하나 골라 즉석 퀴즈를 낸다', effects: { social: 1 }, npcEffects: [{ npcId: 'subin', intimacyChange: 5 }], message: '둘이 단어장으로 티격태격 퀴즈를 낸다. 처음으로 수빈이 공부하다 소리 내 웃는다.', timeCost: 1 },
    ],
  },
  {
    id: 'subin-hs-after',
    reach: { npc: 'subin', tier: 72, year: 7 },
    title: '합격 후',
    description: '합격자 발표가 끝난 며칠 뒤. 수빈이 음료 두 개를 들고 와 하나를 내민다. 예전처럼 들뜬 게 아니라, 조용하다.\n"나 사실 몇 번이나 접으려고 했거든. 엄마 말 들을까, 하고. 근데 네가 한 명은 응원한다고 했잖아. 그 한 명 때문에 못 접겠더라."',
    speakers: ['subin'],
    location: 'classroom',
    background: 'classroom_high',
    condition: (s) => { const n = s.npcs.find(x => x.id === 'subin'); return !!n?.met && n.intimacy >= 72 && s.year === 7; },
    choices: [
      { text: '"포기 안 해줘서 내가 더 고마워"', effects: { mental: 1 }, npcEffects: [{ npcId: 'subin', intimacyChange: 6 }], message: '수빈이 픽 웃는다. "뭐야 그게." 눈가가 붉어진다. "…그 말, 내가 할 말인데."', timeCost: 1, memorySlotDraft: { category: 'reconciliation', importance: 7, toneTag: 'warm', recallText: '음료 두 개, 한 명 때문에 못 접었다던 날.', npcIds: ['subin'] } },
      { text: '"이제 진짜 하늘 위를 날겠네"', effects: { social: 1 }, npcEffects: [{ npcId: 'subin', intimacyChange: 6 }], message: '"그러게." 수빈이 창밖 하늘을 본다. "처음 비행기 사진 보던 날 생각난다." 그 잠금화면이 진짜가 됐다.', timeCost: 1, memorySlotDraft: { category: 'reconciliation', importance: 7, toneTag: 'warm', recallText: '음료 두 개, 한 명 때문에 못 접었다던 날.', npcIds: ['subin'] } },
      { text: '말없이 음료를 부딪쳐 건배한다', effects: { health: 1 }, npcEffects: [{ npcId: 'subin', intimacyChange: 5 }], message: '캔 부딪는 소리. "…고마웠어, 진짜." 수빈이 처음으로 남이 아니라 너한테 속을 다 보인다.', timeCost: 1, memorySlotDraft: { category: 'reconciliation', importance: 7, toneTag: 'warm', recallText: '음료 두 개, 한 명 때문에 못 접었다던 날.', npcIds: ['subin'] } },
    ],
  },
  // ===================== 민재 (minjae) — 무심한 척=방패 / 의대 압박 =====================
  // 기존 캡스톤 dream(Y6,≥65)으로 수렴.
  {
    id: 'minjae-hs-pressure',
    reach: { npc: 'minjae', tier: 58, year: 5 },
    title: '성적표',
    description: '고1 첫 모의고사 성적표가 나왔다. 민재는 또 최상위권. 그런데 표정이 없다. 성적표를 가방에 아무렇게나 구겨 넣는다.\n"이 정도는 당연한 거래, 우리 집은. 잘해도 본전, 못하면 큰일." 무가당 두유를 빤다.',
    speakers: ['minjae'],
    location: 'classroom',
    background: 'classroom_high',
    condition: (s) => { const n = s.npcs.find(x => x.id === 'minjae'); return !!n?.met && n.intimacy >= 58 && s.year === 5 && !s.isVacation; },
    choices: [
      { text: '"당연한 게 어딨어. 잘한 거야"', effects: { mental: 1 }, npcEffects: [{ npcId: 'minjae', intimacyChange: 5 }], message: '"…너는 그렇게 말해주네." 민재가 두유를 입에서 뗀다. 구겨 넣었던 성적표를, 잠깐, 도로 편다.', timeCost: 1 },
      { text: '"본전이라니, 너무하다 그 집"', effects: { social: 1 }, npcEffects: [{ npcId: 'minjae', intimacyChange: 4 }], message: '"뭐, 익숙해." 민재가 어깨를 으쓱한다. 익숙하다는 말이 더 쓸쓸하게 들린다.', timeCost: 1 },
      { text: '"넌 그래서 뭐가 좋은데?"', effects: { mental: 1 }, npcEffects: [{ npcId: 'minjae', intimacyChange: 5 }], message: '민재가 잠깐 멈칫한다. "…그런 거 생각해본 적 없는데." 처음 받아보는 질문이라는 얼굴.', timeCost: 1 },
    ],
  },
  {
    id: 'minjae-hs-doubt',
    reach: { npc: 'minjae', tier: 62, year: 6 },
    title: '진짜 하고 싶은 거',
    description: '야자 시간, 민재가 펜을 놓고 창밖을 본다. 1초도 안 쉬던 애가.\n"야. 너 하고 싶은 거 있어?" 불쑥 묻는다. "난… 의대 가야 된다는 건 아는데, 하고 싶은 건진 모르겠어. 시키는 대로 잘하는 거랑, 하고 싶은 거랑 구분이 안 돼."',
    speakers: ['minjae'],
    location: 'classroom',
    background: 'classroom_high_afternoon',
    condition: (s) => { const n = s.npcs.find(x => x.id === 'minjae'); return !!n?.met && n.intimacy >= 62 && s.year === 6 && !s.isVacation; },
    choices: [
      { text: '"구분 안 되면, 잠깐 멈춰도 돼"', effects: { mental: 1 }, npcEffects: [{ npcId: 'minjae', intimacyChange: 5 }], message: '"멈추면 뒤처지잖아." 민재가 펜을 도로 든다. 근데 글씨를 안 쓴다. 한참을.', timeCost: 1 },
      { text: '"넌 시키는 대로가 아니라 진짜 잘하는 거야"', effects: { social: 1 }, npcEffects: [{ npcId: 'minjae', intimacyChange: 5 }], message: '"…그런가." 민재가 두유를 빤다. "근데 그게 더 무섭다. 잘하니까 더 못 그만두잖아."', timeCost: 1 },
      { text: '"나도 모르겠어. 같이 모르자"', effects: { mental: 1 }, npcEffects: [{ npcId: 'minjae', intimacyChange: 6 }], message: '민재가 처음으로 픽 웃는다. "그게 위로냐." 근데 표정이 조금 풀린다.', timeCost: 1 },
    ],
  },
  {
    id: 'minjae-hs-mask',
    reach: { npc: 'minjae', tier: 70, year: 6 },
    title: '페르소나',
    description: '시험 끝난 날, 다들 노는데 민재만 자습실에 남아 있다. 무심한 척 문제집을 펴는데, 손이 떨린다.\n"…사실 나, 무심한 게 아니라 안 무심한 척을 못 하는 거야. 떨리는 거 들키면 다들 실망하잖아. 노력형은 천재처럼 보여야 되거든."',
    speakers: ['minjae'],
    location: 'classroom',
    background: 'classroom_high_afternoon',
    condition: (s) => { const n = s.npcs.find(x => x.id === 'minjae'); return !!n?.met && n.intimacy >= 70 && s.year === 6 && !s.isVacation; },
    choices: [
      { text: '"나한텐 안 떨어도 돼"', effects: { mental: 2 }, npcEffects: [{ npcId: 'minjae', intimacyChange: 6 }], message: '민재가 문제집에서 손을 뗀다. "…너한텐, 그래도 되나." 떨리던 손을 책상 밑으로 숨기지 않는다, 처음으로.', timeCost: 1, memorySlotDraft: { category: 'growth', importance: 6, toneTag: 'melancholy', recallText: '자습실, 떨리는 손 처음 안 숨기던 날.', npcIds: ['minjae'] } },
      { text: '"천재인 척, 안 힘들어?"', effects: { mental: 1 }, npcEffects: [{ npcId: 'minjae', intimacyChange: 6 }], message: '"힘들지." 민재가 너무 쉽게 인정한다. "근데 이 말 한 것도 네가 처음이야."', timeCost: 1, memorySlotDraft: { category: 'growth', importance: 6, toneTag: 'melancholy', recallText: '자습실, 떨리는 손 처음 안 숨기던 날.', npcIds: ['minjae'] } },
      { text: '말없이 옆자리에 앉아 같이 문제를 푼다', effects: { health: 1 }, npcEffects: [{ npcId: 'minjae', intimacyChange: 5 }], message: '둘이 말없이 연필 소리만 낸다. 민재의 손 떨림이 조금씩 가라앉는다.', timeCost: 1 },
    ],
  },
  {
    id: 'minjae-hs-choice',
    reach: { npc: 'minjae', tier: 75, year: 7 },
    title: '자기 선택',
    description: '고3 진로 상담 주간. 민재가 상담실 앞에서 한참 못 들어간다. 손에 진학 자료가 구겨져 있다.\n"나… 의대 말고 다른 거, 처음으로 입에 올려봤어. 상담쌤한테. 생명공학 연구. …엄마는 아직 몰라." 말해놓고 자기도 놀란 얼굴이다.',
    speakers: ['minjae'],
    location: 'hallway',
    background: 'counseling_hallway',
    condition: (s) => { const n = s.npcs.find(x => x.id === 'minjae'); return !!n?.met && n.intimacy >= 75 && s.year === 7 && !s.isVacation; },
    choices: [
      { text: '"네 입으로 말했으면, 그게 시작이야"', effects: { mental: 2 }, npcEffects: [{ npcId: 'minjae', intimacyChange: 7 }], message: '"…그런가." 민재가 구긴 자료를 편다. "처음으로 내가 고른 칸이야." 손 떨림이 없다.', timeCost: 1, memorySlotDraft: { category: 'discovery', importance: 7, toneTag: 'breakthrough', recallText: '상담실 앞, 처음 내가 고른 칸이라던 민재.', npcIds: ['minjae'] } },
      { text: '"엄마는 내가 옆에 있을 때 같이 말하자"', effects: { mental: 1, social: 1 }, npcEffects: [{ npcId: 'minjae', intimacyChange: 7 }], message: '민재가 너를 본다. "…같이?" 혼자 감당하려던 짐에, 처음으로 한 명이 끼어든다.', timeCost: 1, memorySlotDraft: { category: 'discovery', importance: 7, toneTag: 'breakthrough', recallText: '상담실 앞, 처음 내가 고른 칸이라던 민재.', npcIds: ['minjae'] } },
      { text: '"무섭지? 근데 네 얼굴 지금 좋아 보여"', effects: { mental: 1 }, npcEffects: [{ npcId: 'minjae', intimacyChange: 6 }], message: '"…티 나?" 민재가 옅게 웃는다. 무심한 척이 아니라, 진짜 웃음이다.', timeCost: 1, memorySlotDraft: { category: 'discovery', importance: 7, toneTag: 'breakthrough', recallText: '상담실 앞, 처음 내가 고른 칸이라던 민재.', npcIds: ['minjae'] } },
    ],
  },
  // ===================== 유나 (yuna) — 밝음 뒤 자기검열 / 음대 꿈 =====================
  // 기존 캡스톤 smile(Y7,≥45)으로 수렴. 티어는 캡스톤(45) 아래로 단조 배치.
  {
    id: 'yuna-hs-piano',
    reach: { npc: 'yuna', tier: 38, year: 5 },
    title: '빈 음악실',
    description: '점심시간 비어 있는 음악실. 야자 대신 유나가 피아노 앞에 있다. 시험곡도 아닌, 그냥 좋아하는 곡을 친다.\n"여기 있을 때가 제일 나 같아." 건반에서 손을 떼며 멋쩍게 웃는다. "근데 이런 말 하면 한가하다 그러겠지?"',
    speakers: ['yuna'],
    location: 'music_room',
    background: 'music_room_middle',
    condition: (s) => { const n = s.npcs.find(x => x.id === 'yuna'); return !!n?.met && n.intimacy >= 38 && s.year === 5 && !s.isVacation; },
    choices: [
      { text: '"전혀. 제일 너다운 게 제일 좋은 건데"', effects: { mental: 1 }, npcEffects: [{ npcId: 'yuna', intimacyChange: 4 }], message: '유나가 잠깐 손을 멈춘다. "…그렇게 말해주는 사람 처음이야." 다시 건반에 손을 올린다.', timeCost: 1 },
      { text: '"한 곡 더 쳐줘. 듣고 싶어"', effects: { social: 1 }, npcEffects: [{ npcId: 'yuna', intimacyChange: 4 }], message: '"진짜?" 유나가 신나서 한 곡을 더 친다. 관객이 한 명뿐인데, 무대보다 편해 보인다.', timeCost: 1 },
      { text: '"공부보다 이게 너 살리는 것 같다"', effects: { mental: 1 }, npcEffects: [{ npcId: 'yuna', intimacyChange: 3 }], message: '"…살린다라." 유나가 그 말을 곱씹는다. "맞네. 여기선 숨이 쉬어져."', timeCost: 1 },
    ],
  },
  {
    id: 'yuna-hs-recital',
    reach: { npc: 'yuna', tier: 42, year: 6 },
    title: '콩쿠르 전날',
    description: '교내 콩쿠르 전날, 빈 음악실. 유나 손이 굳어 자꾸 같은 마디에서 틀린다. 평소 밝던 애가 새파랗게 질려 있다.\n"무대 서면… 틀리는 게 다 보이잖아. 작년에 한 번 틀리고 나서, 손이 그걸 기억해버렸어."',
    speakers: ['yuna'],
    location: 'music_room',
    background: 'music_room_middle',
    condition: (s) => { const n = s.npcs.find(x => x.id === 'yuna'); return !!n?.met && n.intimacy >= 42 && s.year === 6 && !s.isVacation; },
    choices: [
      { text: '"틀려도 돼. 내가 제일 앞에서 들을게"', effects: { mental: 1 }, npcEffects: [{ npcId: 'yuna', intimacyChange: 5 }], message: '유나가 너를 본다. "…앞에서?" 굳었던 손가락이 조금 풀린다. "한 명 있다고 생각하면, 칠 수 있을 것 같기도."', timeCost: 1, memorySlotDraft: { category: 'growth', importance: 6, toneTag: 'warm', recallText: '콩쿠르 전날, 한 명만 있으면 칠 수 있겠다던.', npcIds: ['yuna'] } },
      { text: '"작년의 너랑 지금의 너는 달라"', effects: { mental: 1 }, npcEffects: [{ npcId: 'yuna', intimacyChange: 5 }], message: '"…그런가." 유나가 그 마디를 다시 친다. 이번엔 안 틀린다. 한 번은.', timeCost: 1 },
      { text: '말없이 옆에서 박자를 손으로 짚어준다', effects: { social: 1 }, npcEffects: [{ npcId: 'yuna', intimacyChange: 5 }], message: '네 손이 박자를 짚는 동안, 유나가 그 박자에 맞춰 끝까지 친다. "…같이 세주니까 되네."', timeCost: 1 },
    ],
  },
  {
    id: 'yuna-hs-decision',
    reach: { npc: 'yuna', tier: 44, year: 7 },
    title: '결심 직전',
    description: '고3 진로. 유나가 음대 입시 자료와 일반 학과 자료를 양손에 들고 저울질한다.\n"엄마는 안정적인 데 가래. 근데 피아노 놓으면… 나 뭐가 남지." 자료를 번갈아 본다. "결정하기 전에, 너한테 먼저 말하고 싶었어."',
    speakers: ['yuna'],
    location: 'classroom',
    background: 'classroom_high',
    condition: (s) => { const n = s.npcs.find(x => x.id === 'yuna'); return !!n?.met && n.intimacy >= 44 && s.year === 7 && !s.isVacation; },
    choices: [
      { text: '"네가 숨 쉬어지는 쪽으로 가"', effects: { mental: 1 }, npcEffects: [{ npcId: 'yuna', intimacyChange: 5 }], message: '유나가 음악실에서 했던 말을 떠올린 얼굴이다. "…숨 쉬어지는 쪽." 음대 자료를 한 번 더 본다.', timeCost: 1 },
      { text: '"엄마는 내가 같이 설득해줄게"', effects: { social: 1 }, npcEffects: [{ npcId: 'yuna', intimacyChange: 5 }], message: '"같이?" 유나가 처음으로 혼자가 아닌 표정을 짓는다. "…그럼 좀 덜 무섭다."', timeCost: 1 },
      { text: '"둘 다 해보고 정해도 안 늦어"', effects: { mental: 1 }, npcEffects: [{ npcId: 'yuna', intimacyChange: 4 }], message: '"…그래도 되나." 유나가 어깨에서 힘을 조금 푼다. 저울이 잠깐 멈춘다.', timeCost: 1 },
    ],
  },
  // ===================== 준하 (junha) — 부산 전학생 / 요리사 꿈 =====================
  // 기존 캡스톤 cook(Y7,≥38)으로 수렴. Y6 전학이라 Y7 라운드업 2개.
  {
    id: 'junha-hs-recipe',
    reach: { npc: 'junha', tier: 42, year: 7 },
    title: '레시피 노트',
    description: '점심시간 옥상. 준하가 늘 그렇듯 직접 싼 도시락을 꺼내는데, 오늘은 작은 노트도 같이 편다. 레시피가 빼곡하다.\n"요리사 될 거다, 내. 부산 가면 가게 하나 차릴 끼다." 사투리가 꿈 얘기에서 더 진해진다. "엄마 식당, 내가 물려받을 수도 있고."',
    speakers: ['junha'],
    location: 'rooftop',
    background: 'rooftop_sunset',
    condition: (s) => { const n = s.npcs.find(x => x.id === 'junha'); return !!n?.met && n.intimacy >= 42 && s.year === 7 && !s.isVacation; },
    choices: [
      { text: '"메뉴 1호는 주먹밥이어야겠다"', effects: { social: 1 }, npcEffects: [{ npcId: 'junha', intimacyChange: 5 }], message: '준하가 빵 터진다. "맞나? 그라믄 니가 1호 손님 해래이." 노트 첫 장에 네 이름을 적는다.', timeCost: 1 },
      { text: '"노트까지 적는 거 보니 진심이네"', effects: { mental: 1 }, npcEffects: [{ npcId: 'junha', intimacyChange: 5 }], message: '"진심이지. 농담으로 칼 잡나." 준하가 노트를 소중하게 덮는다.', timeCost: 1 },
      { text: '"부산 가면 못 보겠네" 툭', effects: { mental: 1 }, npcEffects: [{ npcId: 'junha', intimacyChange: 4 }], message: '준하가 잠깐 젓가락을 멈춘다. "…그라네. 그 생각은 안 했다." 옥상에 바람이 분다.', timeCost: 1 },
    ],
  },
  {
    id: 'junha-hs-farewell',
    reach: { npc: 'junha', tier: 50, year: 7 },
    title: '다시 부산',
    description: '졸업 무렵, 준하가 교문 앞에서 머뭇거린다. 짐 가방이 평소보다 크다.\n"나 부산 내려간다. 엄마 식당 일도 돕고, 거서 요리 배울라고." 직설적이던 애가 말을 고른다. "여기… 처음엔 여기도 저기도 아닌 것 같았는데. 이젠 여기도 내 자리 같더라. 니 덕분에."',
    speakers: ['junha'],
    location: 'school_gate',
    background: 'school_gate_high',
    condition: (s) => { const n = s.npcs.find(x => x.id === 'junha'); return !!n?.met && n.intimacy >= 50 && s.year === 7; },
    choices: [
      { text: '"부산 가도 연락하자. 1호 손님 약속 지켜야지"', effects: { social: 1 }, npcEffects: [{ npcId: 'junha', intimacyChange: 6 }], message: '"하모. 가게 차리믄 젤 먼저 연락한다." 준하가 새끼손가락을 건다. 사투리가 떨린다.', timeCost: 1, memorySlotDraft: { category: 'reconciliation', importance: 6, toneTag: 'melancholy', recallText: '교문 앞 큰 가방, 여기도 내 자리 같다던 준하.', npcIds: ['junha'] } },
      { text: '"여기가 네 자리였다니 다행이다"', effects: { mental: 1 }, npcEffects: [{ npcId: 'junha', intimacyChange: 6 }], message: '"…니가 그래 만들어줬지." 준하가 처음으로 눈을 안 피하고 말한다.', timeCost: 1, memorySlotDraft: { category: 'reconciliation', importance: 6, toneTag: 'melancholy', recallText: '교문 앞 큰 가방, 여기도 내 자리 같다던 준하.', npcIds: ['junha'] } },
      { text: '말없이 가방 한쪽을 들어준다', effects: { health: 1 }, npcEffects: [{ npcId: 'junha', intimacyChange: 5 }], message: '교문까지 둘이 가방을 나눠 든다. "…이런 거 해주는 친구, 부산엔 없었다." 준하가 웃는데 코끝이 빨갛다.', timeCost: 1, memorySlotDraft: { category: 'reconciliation', importance: 6, toneTag: 'melancholy', recallText: '교문 앞 큰 가방, 여기도 내 자리 같다던 준하.', npcIds: ['junha'] } },
    ],
  },
  // ===================== 하은 (haeun) — 챙기는 선배(1년 위) / 졸업해 떠남 =====================
  // 기존 reunion(Y5,≥15)에서 이어, 1년 위라 Y5~6만. "마지막 줄 비워둘게"와 호응.
  {
    id: 'haeun-hs-rooftop',
    reach: { npc: 'haeun', tier: 28, year: 5 },
    title: '옥상의 선배',
    description: '고교에서 다시 만난 하은 선배. 늘 가던 옥상에서, 이번엔 선배가 네 진로 고민을 들어준다.\n"후배가 고민 상담을 다 하네." 웃으면서도, 하은은 제 얘긴 안 한다. "난 뭐… 잘 지내지. 응, 잘 지내." 한 박자 늦는 대답.',
    speakers: ['haeun'],
    location: 'rooftop',
    background: 'rooftop_sunset',
    condition: (s) => { const n = s.npcs.find(x => x.id === 'haeun'); return !!n?.met && n.intimacy >= 28 && s.year === 5 && !s.isVacation; },
    choices: [
      { text: '"선배는요? 진짜 괜찮아요?" 되묻는다', effects: { mental: 1 }, npcEffects: [{ npcId: 'haeun', intimacyChange: 4 }], message: '하은이 잠깐 말이 없다. "…너는 그걸 묻네." 늘 챙기기만 하던 사람이, 처음 챙김받는 얼굴.', timeCost: 1 },
      { text: '"선배 덕에 저 많이 컸어요"', effects: { social: 1 }, npcEffects: [{ npcId: 'haeun', intimacyChange: 4 }], message: '"내가 뭘 했다고." 하은이 난간을 짚는다. 그래도 입꼬리가 올라간다.', timeCost: 1 },
      { text: '말없이 옥상 난간에 같이 기댄다', effects: { health: 1 }, npcEffects: [{ npcId: 'haeun', intimacyChange: 3 }], message: '둘이 같은 풍경을 본다. "…이렇게 후배랑 옥상 있는 것도 얼마 안 남았네." 하은이 먼저 흘린다.', timeCost: 1 },
    ],
  },
  {
    id: 'haeun-hs-leaving',
    reach: { npc: 'haeun', tier: 40, year: 6 },
    title: '마지막 줄',
    description: '하은 선배의 졸업식. 후배들 틈에서 너를 찾아 다가온다. 손에 낡은 방송부 대본이 들려 있다.\n"이거, 내가 쓰던 대본. 마지막 줄은 네가 채우라고 비워뒀어." 늘 마지막 줄을 비워두던 사람이, 이번엔 그걸 너한테 건넨다. "잘 지내. 연락하고."',
    speakers: ['haeun'],
    location: 'auditorium',
    background: 'auditorium_high',
    condition: (s) => { const n = s.npcs.find(x => x.id === 'haeun'); return !!n?.met && n.intimacy >= 40 && s.year === 6; },
    choices: [
      { text: '"선배 마지막 줄, 제가 꼭 채울게요"', effects: { mental: 1 }, npcEffects: [{ npcId: 'haeun', intimacyChange: 5 }], message: '하은이 옅게 웃는다. "그래. 그게 너답겠다." 비워둔 줄 하나가, 너에게로 넘어온다.', timeCost: 1, memorySlotDraft: { category: 'reconciliation', importance: 6, toneTag: 'melancholy', recallText: '졸업식, 마지막 줄 비워 건네준 선배의 대본.', npcIds: ['haeun'] } },
      { text: '"선배 없으면 이 학교 허전할 거예요"', effects: { social: 1 }, npcEffects: [{ npcId: 'haeun', intimacyChange: 5 }], message: '"금방 또 채워질걸." 하은이 말은 그렇게 하면서, 한참을 안 돌아선다.', timeCost: 1, memorySlotDraft: { category: 'reconciliation', importance: 6, toneTag: 'melancholy', recallText: '졸업식, 마지막 줄 비워 건네준 선배의 대본.', npcIds: ['haeun'] } },
      { text: '"오빠 일은… 선배는 다를 거예요" 조심스레', effects: { mental: 1 }, npcEffects: [{ npcId: 'haeun', intimacyChange: 5 }], message: '하은이 멈칫한다. "…그 얘길 기억하네." 눈가가 잠깐 흔들린다. "응. 나는, 다를게."', timeCost: 1, memorySlotDraft: { category: 'reconciliation', importance: 6, toneTag: 'melancholy', recallText: '졸업식, 마지막 줄 비워 건네준 선배의 대본.', npcIds: ['haeun'] } },
    ],
  },
] satisfies readonly GameEvent[];
