import { GameEvent } from '../types';

// ===== 복원 신규 NPC(seoa·siwoo·yerin) 친밀도 도달형 이벤트 =====
// docs/reach-high-new-npcs.md 확정 아크(작가 파이프라인 ~113 에이전트, drama-caliber). 코드화 + 밸런스 반영.
// 밸런스 A(상한 상향): siwoo Y7 78/80, yerin Y7 58/68 — 기존 88~92 곡선·고티어 scarcity 정합.
// 밸런스 B(메타 보완): siwoo 핵심 3컷·yerin Y5 컷에 memorySlot 메타. (전 컷 슬롯은 후회풀 쏠림 → 학년당 1개꼴)
// yerin Y5 t25는 intro(yerin-meet 단가표)가 흡수 → 도달형은 t40부터(5컷).
export const NEW_NPC_REACH_EVENTS = [
  // ===================== 윤서아 (seoa) — 중2~고3, 내성적 글쟁이 / 읽힐 용기 =====================
  {
    id: 'seoa-onehalf-earphone',
    reach: { npc: 'seoa', tier: 40, year: 2 },
    title: '한쪽 이어폰',
    description: '방과후 복도 끝 창가. 서아가 이어폰을 끼고 노트에 적다 나를 본다. 잠깐 단어를 고르듯 멈추더니, 끼고 있던 한쪽 이어폰을 빼서 내 쪽으로 내민다. 줄이 짧아 한 걸음 들어와야 닿는다.\n서아: "이거 들으면서 쓰면 문장이 좀 더 멀리 가. 한쪽만 줄게. 양쪽 다 주면 네가 옆에서 내는 소리를 못 들으니까. 그건 안 적고 그냥 들으려고."',
    speakers: ['seoa'],
    location: 'hallway',
    background: 'hallway_middle',
    condition: (s) => { const n = s.npcs.find(x => x.id === 'seoa'); return !!n?.met && n.intimacy >= 40 && s.year === 2 && !s.isVacation; },
    choices: [
      { text: '한 걸음 들어가 같이 듣는다', effects: { mental: 2 }, npcEffects: [{ npcId: 'seoa', intimacyChange: 9 }], message: '둘이 한쪽씩 끼고 창밖을 본다. 줄 길이만큼만 가까운 거리. 한 곡이 끝나도 서아가 다음 곡을 안 넘긴다. "이 노래, 끝까지 들은 사람 처음이야."', timeCost: 1, memorySlotDraft: { category: 'discovery', importance: 6, toneTag: 'warm', recallText: '한쪽만 줄게, 네가 내는 소리는 안 적고 들을게.', npcIds: ['seoa'] } },
      { text: '받되 "무슨 곡인데" 화면 쪽으로 손이 간다', effects: { social: 1 }, npcEffects: [{ npcId: 'seoa', intimacyChange: 5 }], message: '서아가 화면을 살짝 돌려놓는다. "…아직. 곡목은 끝나면. 끝나긴 할까." 이어폰은 준 채, 한 칸은 열고 한 칸은 닫는다.', timeCost: 1 },
      { text: '"공부할 시간 아냐?"', effects: { mental: 1 }, npcEffects: [{ npcId: 'seoa', intimacyChange: 1 }], message: '내민 이어폰을 도로 자기 귀에 끼운다. "…그렇지. 시간 아깝지." 사각거리던 펜이 멈춘다.', timeCost: 1 },
    ],
  },
  {
    id: 'seoa-unfinished-face',
    reach: { npc: 'seoa', tier: 60, year: 2 },
    title: '적다 만 표정',
    description: '비 오는 날 교실. 다들 떠드는데 서아만 창가에서 펜을 멈추지 않는다. 옆에 앉자 처음으로 노트를 덮지 않고 펼친 채 둔다. 반 아이들 이름 옆에 짧은 문장이 한 줄씩 적혀 있는데, 내 이름 칸만 적다 만 듯 중간에서 끊겨 있다.\n서아: "사람 표정을 적어. 금방 지나가거든, 표정은. 비처럼. 너 건 적으려고 보면 그새 딴 표정이 돼 있어. 그래서 늘 도중에 끊겨."',
    speakers: ['seoa'],
    location: 'classroom',
    background: 'classroom_middle_afternoon',
    condition: (s) => { const n = s.npcs.find(x => x.id === 'seoa'); return !!n?.met && n.intimacy >= 60 && s.year === 2 && !s.isVacation; },
    choices: [
      { text: '"지금 거 적어. 안 움직일게" 멈춰 있어 준다', effects: { mental: 2 }, npcEffects: [{ npcId: 'seoa', intimacyChange: 9 }], message: '서아가 나를 오래 본다. 펜이 사각거리다 멈춘다. "…안 적을래. 지금 거는 그냥 보고 있을게." 끝내 안 적고 펜을 내려놓는다.', timeCost: 1, memorySlotDraft: { category: 'discovery', importance: 6, toneTag: 'melancholy', recallText: '네 표정은 적으려 보면 그새 딴 표정이 돼 있었다.', npcIds: ['seoa'] } },
      { text: '"넌 왜 늘 적기만 해, 같이 떠들면 되잖아"', effects: { social: 1, mental: -1 }, npcEffects: [{ npcId: 'seoa', intimacyChange: 5 }], message: '"안에 들어가면, 밖이 안 보여서." 시선이 노트로 돌아간다. 펜이 한 박자 빨라진다.', timeCost: 1 },
      { text: '펼친 노트를 가만히 덮어준다', effects: { mental: 1 }, npcEffects: [{ npcId: 'seoa', intimacyChange: 6 }], message: '"비 그치고 봐"라는 말도 없이 그냥. 서아가 손등으로 페이지를 한 번 쓸고 픽 웃는다. "…방금 그것도 적고 싶어졌는데. 손이 안 움직이네."', timeCost: 1 },
    ],
  },
  {
    id: 'seoa-not-like-me',
    reach: { npc: 'seoa', tier: 70, year: 3 },
    title: '나답지 않다는 말',
    description: '중3 가을, 교지 마감 다음 날. 서아가 게시판 앞에 서 있다. 합격작 명단에 서아 이름은 없다. 이어폰을 양쪽 다 꽂고 있다 — 이제 나는 그게 \'아무것도 듣지 않겠다\'는 뜻인 걸 안다. 손엔 돌려받은 원고가 반으로 접혀 있고, 위에 빨간 글씨로 \'너무 어둡다, 중학생답게\'가 적혀 있다.\n서아: (한쪽 이어폰을 뺀다, 나한테만) "…떨어졌어. 너무 어둡대. 나답게 썼더니, 나답지 않다고 하더라. 그럼 나다운 건 어디서 자랐길래 나한테 없는 거지."',
    speakers: ['seoa'],
    location: 'hallway',
    background: 'hallway_middle',
    condition: (s) => { const n = s.npcs.find(x => x.id === 'seoa'); return !!n?.met && n.intimacy >= 70 && s.year === 3 && !s.isVacation; },
    choices: [
      { text: '"근데 나는 그 글이 자꾸 다시 읽히더라" 두 진실을 다 연다', effects: { mental: 2 }, npcEffects: [{ npcId: 'seoa', intimacyChange: 9 }], message: '서아가 빼던 이어폰을 도로 안 낀다. 한참. "…너 하나면 됐는데, 왜 자꾸 더. 이런 건 안 적어둬야 하는데." 적으려다 만 손을 주머니에 넣는다.', timeCost: 1, memorySlotDraft: { category: 'failure', importance: 7, toneTag: 'regret', recallText: '나다움은 어디서 자랐길래 나한테 없을까.', npcIds: ['seoa'] } },
      { text: '"그쪽이 좋아할 걸 한 번 써봐" 현실을 권한다', effects: { mental: -1 }, npcEffects: [{ npcId: 'seoa', intimacyChange: 2 }], message: '서아가 빤히 본다. "…그럼 그게 내 글이야? 합격이 나야, 글이 나야." 답을 안 듣고 도로 양쪽을 낀다.', timeCost: 1 },
      { text: '말없이 옆에서 같이 빈 명단을 본다', effects: { mental: 2 }, npcEffects: [{ npcId: 'seoa', intimacyChange: 7 }], message: '한참 뒤. "…안 물어봐줘서. 다들 뭐라도 해주려고 하던데." 접힌 원고를 펴지도 버리지도 않는다.', timeCost: 1 },
    ],
  },
  {
    id: 'seoa-torn-endless-line',
    reach: { npc: 'seoa', tier: 85, year: 4 },
    title: '끝없는 줄을 찢어 쥐여준다',
    description: '중학교 졸업식 날. 강당 밖, 서아가 3년간 적어온 그 노트를 꺼낸다. 음악실에서 처음 본 날 가슴에 끌어안고 안 보여주던 노트다. 한참 가장자리를 손가락으로 따라가다, 한 장을 천천히 찢는다. 거기엔 한 줄이 적혀 있는데, 끝이 없다 — 마침표 없이 도중에 끊긴 채다.\n서아: "처음 본 날엔 이거 가슴에 안고 있었잖아. 이젠 찢어서도 주네. 이 줄, 끝이 없지. 내가 진짜로 쓰는 사람이 되면, 그때 끝을 데리러 올게. 그때까지 네가 갖고 있어."',
    speakers: ['seoa'],
    location: 'auditorium',
    background: 'auditorium_middle',
    condition: (s) => { const n = s.npcs.find(x => x.id === 'seoa'); return !!n?.met && n.intimacy >= 85 && s.year === 4; },
    choices: [
      { text: '"데리러 올 때까지 갖고 있을게" 약속한다', effects: { mental: 2 }, npcEffects: [{ npcId: 'seoa', intimacyChange: 9 }], message: '서아가 페이지를 마저 손에 쥐여준다. 손이 잠깐 안 놓아진다. 4년간 끝을 못 고치는 줄 하나를, 내게 맡긴 셈이 된다.', timeCost: 1, memorySlotDraft: { category: 'growth', importance: 7, toneTag: 'burden', recallText: '끝을 데리러 오겠다며, 끝없는 줄을 찢어 쥐여줬다.', npcIds: ['seoa'] } },
      { text: '"지금 끝내주면 안 돼?" 되묻는다', effects: { mental: 1 }, npcEffects: [{ npcId: 'seoa', intimacyChange: 6 }], message: '"안 돼. 지금 쓰면 지금의 나로 끝나버려서." 살짝 웃으며 빈 끝을 일부러 남긴다.', timeCost: 1 },
      { text: '페이지를 받지만 약속은 하지 않는다', effects: { mental: 1 }, npcEffects: [{ npcId: 'seoa', intimacyChange: 3 }], message: '"…그래. 약속은 적어둔 거랑 달라서, 자꾸 달라지니까." 끝없는 줄이 끝없는 채로 내 손에 남는다.', timeCost: 1 },
    ],
  },
  {
    id: 'seoa-both-earphones-again',
    reach: { npc: 'seoa', tier: 50, year: 5 },
    title: '도로 양쪽 다',
    description: '고1 야간자율학습 첫 주. 형광등 줄지은 책상 맨 끝, 낯익은 긴 머리 — 같은 고등학교에 왔다. 서아는 이어폰을 양쪽 다 꽂고 문제집을 본다(닫힘 코드). 문제집 밑으로 노트 모서리가 삐져나와 있다. 내가 옆에 서자, 한 페이지를 넘길 시간만큼 지나 한쪽을 뺀다.\n서아: "…너도 왔구나. 이건 그냥 손이 심심해서. 여긴 다들 문제집만 보니까, 노트 펴면 좀… 아니, 펴도 되는데."',
    speakers: ['seoa'],
    location: 'classroom',
    background: 'classroom_high_afternoon',
    condition: (s) => { const n = s.npcs.find(x => x.id === 'seoa'); return !!n?.met && n.intimacy >= 50 && s.year === 5 && !s.isVacation; },
    choices: [
      { text: '"그거 아직 쓰는구나" 삐져나온 모서리를 알아봐준다', effects: { mental: 1 }, npcEffects: [{ npcId: 'seoa', intimacyChange: 8 }], message: '서아가 밀어넣던 노트를 도로 빼낸다. "…너만 이게 노트인 줄 아네. 남들 눈엔 다 똑같은 종이야."', timeCost: 1, memorySlotDraft: { category: 'reconciliation', importance: 5, toneTag: 'warm', recallText: '남들 눈엔 똑같은 종이를, 너만 노트로 봤다.', npcIds: ['seoa'] } },
      { text: '"여기도 문이 두 번에 열리는 데 있으려나" 음악실 첫날을 소환한다', effects: { mental: 1 }, npcEffects: [{ npcId: 'seoa', intimacyChange: 6 }], message: '서아가 처음으로 양쪽 다 뺀다. "…찾아보자. 경첩이 뻑뻑한 데로." 줄을 둘둘 감는다.', timeCost: 1 },
      { text: '"이제 입시잖아, 그건 좀 접어두자"', effects: { mental: -1 }, npcEffects: [{ npcId: 'seoa', intimacyChange: 1 }], message: '뺐던 이어폰을 도로 양쪽 다 낀다. 노트를 문제집 밑으로 완전히 밀어넣는다. 시선을 내린다.', timeCost: 1 },
    ],
  },
  {
    id: 'seoa-clearer-handwriting',
    reach: { npc: 'seoa', tier: 65, year: 6 },
    title: '더 또박또박한 글씨',
    description: '고2 진로상담 주간. 야자 끝난 빈 교실, 서아가 진로희망서를 펴두고 펜만 굴린다. 가까이 보니 1지망 칸에 서아 글씨로 적힌 글자 위에 두 줄이 그어졌고, 그 위에 더 또박또박한 다른 글씨로 고쳐 적혀 있다. 엄마 글씨다.\n서아: "내 글씨보다 엄마가 고쳐 쓴 글씨가 더 또박또박해. 내 칸인데 내 손글씨가 제일 흐려. …네가 갖고 있는 그 페이지. 끝, 이제 못 데리러 갈지도 몰라."',
    speakers: ['seoa'],
    location: 'classroom',
    background: 'classroom_high_afternoon',
    condition: (s) => { const n = s.npcs.find(x => x.id === 'seoa'); return !!n?.met && n.intimacy >= 65 && s.year === 6 && !s.isVacation; },
    choices: [
      { text: '"그럼 끝은 내가 계속 데리고 있을게" 부담을 거둔다', effects: { mental: 2 }, npcEffects: [{ npcId: 'seoa', intimacyChange: 9 }], message: '서아가 펜을 내려놓는다. "…그렇게 말하는 사람이 하나 있으니까, 노트를 아직 못 버리겠어." 4년 전 줄이 둘의 것이 된다.', timeCost: 1, memorySlotDraft: { category: 'growth', importance: 7, toneTag: 'burden', recallText: '내 칸인데 내 손글씨가 제일 흐렸다.', npcIds: ['seoa'] } },
      { text: '"두 줄 위에, 네 글씨로 한 번 더 적어" 행동을 권한다', effects: { mental: 1 }, npcEffects: [{ npcId: 'seoa', intimacyChange: 6 }], message: '서아가 두 줄 위에 자기 글씨를 겹쳐 쓴다. 손이 떨려 더 흐리다. "…더 안 보이게 됐네. 근데 적긴 적었다."', timeCost: 1 },
      { text: '"엄마 말도 일리는 있잖아" 현실을 든다', effects: { mental: -1 }, npcEffects: [{ npcId: 'seoa', intimacyChange: 2 }], message: '"…너까지 또박또박하게 말하면, 나는 어디서 흐릴 수 있어." 희망서를 접는다. 이어폰을 한쪽 낀다.', timeCost: 1 },
    ],
  },
  {
    id: 'seoa-name-blank',
    reach: { npc: 'seoa', tier: 75, year: 7 },
    title: '제목 칸',
    description: '고3 봄, 입시 막바지. 야자 끝난 교실에 서아가 남아 전국 청소년 백일장 신청서를 만진다. 마감은 오늘 밤. 다른 칸은 다 채웠는데 제목 칸만 비어 있다. 옆엔 수시 자소서 출력물 — 첨삭 약속이 오늘 잡혀 있다. 둘 중 하나를 할 시간밖에 없다.\n서아: "이거 내면 그날 자소서 첨삭 못 받아. 둘 다는 안 돼. (제목 칸을 펜 끝으로 톡톡 친다, 안 적고) 내 글에 제목 다는 거, 왜 이게 제일 어렵지. 다른 칸은 다 채웠는데."',
    speakers: ['seoa'],
    location: 'classroom',
    background: 'classroom_high_afternoon',
    condition: (s) => { const n = s.npcs.find(x => x.id === 'seoa'); return !!n?.met && n.intimacy >= 75 && s.year === 7 && !s.isVacation; },
    choices: [
      { text: '"떨어져도, 적고 싶은 칸에 떨어지는 거잖아" 등을 민다', effects: { mental: 3 }, npcEffects: [{ npcId: 'seoa', intimacyChange: 9 }], message: '서아가 한참 만에 제목을 적는다. 한 글자씩. "…네가 옆에서 보고 있으니까 손이 움직이네. 이번엔 안 도망쳐." 자소서 출력물을 서랍에 넣는다.', timeCost: 1, memorySlotDraft: { category: 'growth', importance: 7, toneTag: 'resolve', recallText: '제목 칸 하나가 다른 모든 칸보다 무거웠다.', npcIds: ['seoa'] } },
      { text: '"현실도 봐야지. 자소서가 먼저 아닐까" 현실을 짚는다', effects: { mental: -1 }, npcEffects: [{ npcId: 'seoa', intimacyChange: 4 }], message: '"…너답다. 맞는 말이라 더 미루고 싶어지네." 신청서를 서랍에 반쯤 넣다 만다.', timeCost: 1 },
      { text: '"네가 정해. 뭘 골라도 네 편이야" 무게를 돌려준다', effects: { mental: 1 }, npcEffects: [{ npcId: 'seoa', intimacyChange: 7 }], message: '"…그 말이 제일 무거워. 결국 펜은 내가 쥐어야 하니까." 톡톡 치던 펜을 고쳐 쥔다.', timeCost: 1 },
    ],
  },
  {
    id: 'seoa-ending-page',
    reach: { npc: 'seoa', tier: 90, year: 7 },
    title: '끝을 데려온 페이지',
    description: '고등학교 졸업식 날. 4년 전 찢어 쥐여줬던 그 페이지 — 끝이 끊겨 있던 한 장 — 을 서아가 들고 나를 찾아온다. 음악실 첫날처럼 한쪽 이어폰을 뺀 채, 페이지를 가리지 않는다. 끊겨 있던 줄의 끝에 이제 글씨가 채워져 있다. 잉크 색이 4년 전과 다르다.\n서아: "기억나? 쓰는 사람 되면 끝을 데리러 온다고 했잖아. 알았어 — 작가가 돼서 끝이 오는 게 아니라, 읽어줄 한 사람이 생겨서 끝이 따라오는 거더라. 그래서 이 줄, 네가 문 열던 소리로 시작해. 경첩이 두 번 울리던, 그."',
    speakers: ['seoa'],
    location: 'auditorium',
    background: 'auditorium_high',
    condition: (s) => { const n = s.npcs.find(x => x.id === 'seoa'); return !!n?.met && n.intimacy >= 90 && s.year === 7; },
    choices: [
      { text: '채워진 줄을 끝까지 읽는다', effects: { mental: 3 }, npcEffects: [{ npcId: 'seoa', intimacyChange: 10 }], message: '첫 줄은 음악실 경첩이 두 번 울리던 소리로 시작한다. 다 읽는 동안 서아는 이어폰도 안 낀 채 가만히 기다린다. 끊겨 있던 끝자리엔, 내 이름이 적혀 있다.', timeCost: 1, memorySlotDraft: { category: 'reconciliation', importance: 8, toneTag: 'warm', recallText: '경첩이 두 번 울리던 소리로 시작하던, 끝이 채워진 줄.', npcIds: ['seoa'] } },
      { text: '"나도 너한테 못 적은 줄 있어" 마주 꺼낸다', effects: { social: 1, mental: 2 }, npcEffects: [{ npcId: 'seoa', intimacyChange: 9 }], message: '둘 다 이어폰을 뺀 채, 강당 밖에서 서로 미뤄둔 줄을 처음으로 소리 내 읽는다. "…너도 끝을 미뤄뒀구나."', timeCost: 1, memorySlotDraft: { category: 'reconciliation', importance: 8, toneTag: 'warm', recallText: '경첩이 두 번 울리던 소리로 시작하던, 끝이 채워진 줄.', npcIds: ['seoa'] } },
      { text: '"끝까지 못 봤으면 어쩔 뻔했어" 웃는다', effects: { mental: 2 }, npcEffects: [{ npcId: 'seoa', intimacyChange: 8 }], message: '"…나도. 그래서 오늘은 안 고치고 안 미뤘어. 미루다 못 본 줄이, 너무 많아서." 페이지를 내 손에 쥐여준다. 이번엔 안 찢고 통째로.', timeCost: 1, memorySlotDraft: { category: 'reconciliation', importance: 8, toneTag: 'warm', recallText: '경첩이 두 번 울리던 소리로 시작하던, 끝이 채워진 줄.', npcIds: ['seoa'] } },
    ],
  },
  // ===================== 한시우 (siwoo) — 고1~고3, 관찰자·건축꿈 / 소실점은 한 사람 =====================
  {
    id: 'siwoo-invisible-narrowing',
    reach: { npc: 'siwoo', tier: 30, year: 5 },
    title: '안 보이는 게 더 이상한 거',
    description: '쉬는 시간, 시우 자리를 지나는데 그가 텀블러 든 손으로 창밖을 가리킨다. 운동장 구석, 애들이 매번 같은 자리에서 서로 부딪혀 길을 비킨다. 며칠째 같은 시간에 그것만 보고 있던 사람처럼 말한다.\n시우: "저기, 매일 똑같은 자리에서 부딪혀. 길이 거기서 좁아지거든. 아무도 안 고치고 다들 비켜만 줘. …안 보이는 게 더 이상하지 않아? 매일 거기서 부딪히는데."',
    speakers: ['siwoo'],
    location: 'classroom',
    background: 'classroom_high',
    condition: (s) => { const n = s.npcs.find(x => x.id === 'siwoo'); return !!n?.met && n.intimacy >= 30 && s.year === 5 && !s.isVacation; },
    choices: [
      { text: '"고치려면 어디부터 봐야 돼?" 그의 보는 법에 올라탄다', effects: { mental: 2 }, npcEffects: [{ npcId: 'siwoo', intimacyChange: 6 }], message: '시우가 창문 따라 손가락으로 길을 다시 긋는다, 평소보다 빠르게. "여기서 한 발만 비켜 서면 돼. 길이 아니라 사람이."', timeCost: 1 },
      { text: '"넌 부딪히는 쪽이야, 비켜 주는 쪽이야?" 정곡', effects: { mental: 1 }, npcEffects: [{ npcId: 'siwoo', intimacyChange: 5 }], message: '시우가 잠깐 말이 없다. "…비켜 주는 쪽. 부딪히면 양쪽 다 멈추잖아." 텀블러를 도로 든다.', timeCost: 1 },
      { text: '"피곤하겠다, 다 그렇게 보고 살면" 가볍게', effects: { social: 1 }, npcEffects: [{ npcId: 'siwoo', intimacyChange: 3 }], message: '"가끔." 한 박자 늦게 픽 웃는다.', timeCost: 1 },
    ],
  },
  {
    id: 'siwoo-last-signal',
    reach: { npc: 'siwoo', tier: 45, year: 5 },
    title: '신호 끝물',
    description: '하굣길, 우연히 같은 방향. 횡단보도 앞에서 시우가 신호가 초록으로 바뀌어도 안 건넌다. 다들 건너가고, 그는 텀블러를 든 채 한 박자, 두 박자를 흘려보낸다. 깜빡이기 시작할 때서야 천천히 발을 뗀다.\n시우: (너 방금 초록인데 안 건넜어, 하고 짚으면 멈칫한다) "…들켰네. 끝물에 건너면 아무도 없어. 가운데서 누구랑도 안 마주쳐. 남 동선은 다 보면서, 내 동선은 이렇게 짜."',
    speakers: ['siwoo'],
    location: 'street',
    background: 'bus_stop_evening',
    condition: (s) => { const n = s.npcs.find(x => x.id === 'siwoo'); return !!n?.met && n.intimacy >= 45 && s.year === 5; },
    choices: [
      { text: '"마주치는 게 그렇게 싫어?" 그 회피를 정면으로', effects: { mental: 2 }, npcEffects: [{ npcId: 'siwoo', intimacyChange: 7 }], message: '시우가 텀블러를 만지작. "싫은 건 아니고. …끝물엔 비켜 줄 사람이 없으니까." 들킨 채로 안 도망간다.', timeCost: 1 },
      { text: '"오늘은 끝물 말고 같이 건너자" 그의 동선에 끼어든다', effects: { social: 2 }, npcEffects: [{ npcId: 'siwoo', intimacyChange: 6 }], message: '다음 초록에 둘이 같이 건넌다. 가운데서 마주 오는 사람과 시우가, 처음으로 안 비킨다. 대신 끝물의 그 빈 횡단보도는, 이제 그 혼자만의 것이 아니게 된다.', timeCost: 1 },
      { text: '말없이 다음 끝물까지 옆에서 같이 기다린다', effects: { mental: 1 }, npcEffects: [{ npcId: 'siwoo', intimacyChange: 5 }], message: '둘이 나란히 두 박자를 흘려보낸다. "…옆에 누가 끝물 기다리는 거, 처음이야."', timeCost: 1 },
    ],
  },
  {
    id: 'siwoo-unbuilt-spot',
    reach: { npc: 'siwoo', tier: 60, year: 5 },
    title: '아직 안 선 자리',
    description: '방과후, 시우가 동네 빈 공터가 내려다보이는 옥상 난간에 기대 있다. 평소엔 헐리는 데만 보던 그가, 오늘은 아무것도 없는 공터를 오래 본다. 손가락으로 허공에 윤곽을 짓는데, 모든 선이 공터의 한 점으로만 모인다. 그 한 점만은 끝까지 손끝으로 안 짚는다.\n시우: "나 맨날 없어지는 데만 봤잖아. 오늘은 처음으로 아직 아무것도 안 선 데를 보고 있어. …저기가 소실점이거든. 다 거길 향하는데. ...아니다." 말을 삼키고 난간을 짚는다.',
    speakers: ['siwoo'],
    location: 'rooftop',
    background: 'rooftop_sunset',
    condition: (s) => { const n = s.npcs.find(x => x.id === 'siwoo'); return !!n?.met && n.intimacy >= 60 && s.year === 5 && !s.isVacation; },
    choices: [
      { text: '"끝까지 말해. 저 점이 누구 보는 자린데" 캐묻는다', effects: { mental: 3 }, npcEffects: [{ npcId: 'siwoo', intimacyChange: 5 }], message: '시우가 입을 닫는다. "…말하면 안 짓게 돼." 그날 더는 안 열린다. 대신 며칠 뒤 문자 한 통: "완성되면 데려올게. 그때까지 같이 와." 미래는 얻었지만, 그 한 점이 누구인지는 끝내 못 듣는다.', timeCost: 1, memorySlotDraft: { category: 'discovery', importance: 6, toneTag: 'melancholy', recallText: '선이 전부 한 점으로 모이던 공터, 끝내 안 짚은 자리.', npcIds: ['siwoo'] } },
      { text: '더 안 묻고 같이 그 한 점을 본다', effects: { mental: 1 }, npcEffects: [{ npcId: 'siwoo', intimacyChange: 8 }], message: '시우가 텀블러를 도로 든다. 캐묻지 않은 그 자리에서, 평소보다 한참을 더 머문다. 공터는 끝내 \'이름 없는 소실점\'으로 남는다 — 지금은 가까워졌지만, 그 점이 누구였는지는 영영 안 들린다.', timeCost: 1, memorySlotDraft: { category: 'discovery', importance: 6, toneTag: 'melancholy', recallText: '선이 전부 한 점으로 모이던 공터, 끝내 안 짚은 자리.', npcIds: ['siwoo'] } },
      { text: '"안 선 거 보니까 너 같다" 가볍게', effects: { social: 1 }, npcEffects: [{ npcId: 'siwoo', intimacyChange: 5 }], message: '"나 같다는 게 뭔지 나도 모르겠는데, 너가 그러면 그런가 보다." 한 박자 늦게 픽.', timeCost: 1 },
    ],
  },
  {
    id: 'siwoo-hand-first',
    reach: { npc: 'siwoo', tier: 62, year: 6 },
    title: '손이 먼저 나갔다',
    description: '고2 체육대회 준비. 반이 응원석 동선으로 엉켜 싸우는 중. 시우는 늘 그렇듯 스탠드 맨 위에서 텀블러를 든 채 보고만 있다. 그런데 갑자기 내려와 바닥에 분필로 동선을 슥슥 긋는다. "여기 막히니까 이쪽으로 빠져." 반이 조용해졌다가 "오" 한다. 시우 본인이 제일 놀란 얼굴이다.\n시우: "…나도 모르게 발이 갔네. 중학교 때 축제 다 짠 적 있어. 근데 당일엔, 내가 짠 자리에 다들 서 있는데 정작 거기 내 자리는 없더라. 그 뒤론 늘 맨 위 칸이더라, 발이."',
    speakers: ['siwoo'],
    location: 'gym',
    background: 'gymnasium',
    condition: (s) => { const n = s.npcs.find(x => x.id === 'siwoo'); return !!n?.met && n.intimacy >= 62 && s.year === 6 && !s.isVacation; },
    choices: [
      { text: '"이번엔 네 자리도 여기 있잖아" 바닥의 선을 가리킨다', effects: { mental: 3 }, npcEffects: [{ npcId: 'siwoo', intimacyChange: 8 }], message: '시우가 제가 그은 선을 본다. "…이번엔 그러네." 처음으로 주머니에서 두 손을 다 뺀다. 위에서 다 보이던 시야는, 이제 없다.', timeCost: 1 },
      { text: '"끼는 거, 위에서 보던 거보다 너한테 어울려" 변화를 짚는다', effects: { mental: 2 }, npcEffects: [{ npcId: 'siwoo', intimacyChange: 7 }], message: '시우가 분필을 만지작. "…그런가." 선을 안 지운다.', timeCost: 1 },
      { text: '"같이 마저 긋자" 옆에 쪼그려 앉는다', effects: { social: 3 }, npcEffects: [{ npcId: 'siwoo', intimacyChange: 7 }], message: '둘이 동선을 마저 긋는다. 반 애들이 둘러선다. 시우가 위가 아니라 한가운데 쪼그려 있다.', timeCost: 1 },
    ],
  },
  {
    id: 'siwoo-demolished-ground',
    reach: { npc: 'siwoo', tier: 75, year: 6 },
    title: '정들면 헐리는 지반',
    description: '비 오는 날, 시우가 데려간 곳은 그가 어릴 때 살던 골목이다. 절반이 펜스로 막혀 철거 중. 그는 펜스 틈으로 한 집의 빈터를 본다. 평소보다 오래, 시선을 안 옮긴다. 텀블러는 비었는데 든 손만 만지작거린다. 빗물이 빈터 한쪽으로만 안 흐르고 고인다.\n시우: "저기, 우리 집 있던 자리. 마당에 평상 하나 있었어. 비 오면 평상으로 물 안 가게, 누가 흙으로 턱을 높여놨더라. 손으로. 지금도 거기만 물이 안 가. …막을 사람이 없어진 자린데, 막아둔 손만 남았어."',
    speakers: ['siwoo'],
    location: 'street',
    background: 'school_entrance_rain',
    condition: (s) => { const n = s.npcs.find(x => x.id === 'siwoo'); return !!n?.met && n.intimacy >= 75 && s.year === 6; },
    choices: [
      { text: '"그 평상, 네 기억엔 아직 안 헐렸잖아" 머무름을 허락한다', effects: { mental: 2 }, npcEffects: [{ npcId: 'siwoo', intimacyChange: 8 }], message: '시우가 빈터를 오래 본다. "…여긴 아직 펜스가 없네." 안 헐렸다고도 안 헐린다고도 안 한다. 다음 만남에도 그는 자꾸 헐린 자리로 데려간다.', timeCost: 1, memorySlotDraft: { category: 'growth', importance: 7, toneTag: 'burden', recallText: '막을 사람은 없는데, 턱 높여 비를 막아둔 빈터.', npcIds: ['siwoo'] } },
      { text: '"언젠가 네가 여기 다시 뭐든 세우면, 나 보러 올게" 미래로 끌어낸다', effects: { mental: 3 }, npcEffects: [{ npcId: 'siwoo', intimacyChange: 7 }], message: '시우가 펜스 너머 빈터를 다르게 본다. "…턱부터 다시 높여야겠다." 헐린 자리에서 처음으로 \'세울 것\'을 본다. 이후 그는 헐린 데보다 안 선 데로 데려간다.', timeCost: 1, memorySlotDraft: { category: 'growth', importance: 7, toneTag: 'burden', recallText: '막을 사람은 없는데, 턱 높여 비를 막아둔 빈터.', npcIds: ['siwoo'] } },
      { text: '말없이 펜스 옆에 같이 선다', effects: { mental: 2 }, npcEffects: [{ npcId: 'siwoo', intimacyChange: 7 }], message: '빗소리만 한참. 빈 텀블러에 빗물이 고인다.', timeCost: 1, memorySlotDraft: { category: 'growth', importance: 7, toneTag: 'burden', recallText: '막을 사람은 없는데, 턱 높여 비를 막아둔 빈터.', npcIds: ['siwoo'] } },
    ],
  },
  {
    id: 'siwoo-hobby-seat',
    reach: { npc: 'siwoo', tier: 78, year: 7 },
    title: '취미로 하라는 자리',
    description: '고3 진로 상담 주간. 시우가 비상계단 참에 앉아 있다. 거기서 동네가 한눈에 보인다. 평소답지 않게 텀블러도 없이, 진학 안내서를 무릎에 펴두고 \'건축학과\'에 가위표를 쳐놨다.\n시우: "아빠가, 건축은 밤새는 직업이라고. 안정적인 데 가고 도면은 취미로 하래. …매일 보는 게 취미면, 그럼 나한테 남는 거 말고, 매일 보는 거 말고 — 진짜는 뭐가 되는 거야. 너는 어떻게 생각해. 봐주지 말고."',
    speakers: ['siwoo'],
    location: 'hallway',
    background: 'counseling_hallway',
    condition: (s) => { const n = s.npcs.find(x => x.id === 'siwoo'); return !!n?.met && n.intimacy >= 78 && s.year === 7 && !s.isVacation; },
    choices: [
      { text: '"네가 매일 서서 보는 자리가 거기면, 답은 벌써 나와 있잖아" 편을 든다', effects: { mental: 3 }, npcEffects: [{ npcId: 'siwoo', intimacyChange: 8 }], message: '시우가 안내서를 접지 않고, 건축학과 칸이 위로 오게 펴서 무릎에 그대로 둔다. "…들어줘서." 끝까지 고맙다곤 안 한다.', timeCost: 1 },
      { text: '"밤새도 너답겠다" 본질을 인정', effects: { mental: 2 }, npcEffects: [{ npcId: 'siwoo', intimacyChange: 7 }], message: '시우가 한참 뒤 픽. "…그건 맞아." 구긴 안내서를 도로 편다.', timeCost: 1 },
      { text: '"아버지 말이 틀린 것도 아니잖아" 현실', effects: { mental: 1 }, npcEffects: [{ npcId: 'siwoo', intimacyChange: 4 }], message: '"…알아. 맞는 말인 거 알아서." 가위표 친 칸을 손톱으로 한 번 눌러 자국을 낸다. 이후 그는 옥상 대신 자습실에 보이기 시작한다.', timeCost: 1 },
    ],
  },
  {
    id: 'siwoo-where-you-stood',
    reach: { npc: 'siwoo', tier: 80, year: 7 },
    title: '전부 네가 서 있던 자리더라',
    description: '졸업식 직전, 시우가 데려간 곳은 학교 옥상이다. 처음 만난 날 3주째 멈췄던 그 크레인 자리엔 이제 아파트 한 동이 다 올라가 있다. 그는 난간에 텀블러를 내려놓고, 손가락으로 동네 곳곳을 천천히 짚는다. 가리키는 건 전부 \'자리\'다.\n시우: "저 횡단보도, 끝물에만 건너던 데. 저 공터, 선이 다 한 점으로 모이던 데. 저 펜스, 평상 자리. …돌아보니까, 내가 자리를 본 게 아니더라. 전부 네가 서 있던 자리였어. 건물은 헐려도, 누가 어디 섰는지는 안 헐리거든."',
    speakers: ['siwoo'],
    location: 'rooftop',
    background: 'rooftop_sunset',
    condition: (s) => { const n = s.npcs.find(x => x.id === 'siwoo'); return !!n?.met && n.intimacy >= 80 && s.year === 7; },
    choices: [
      { text: '"그 자리들, 평생 안 잊을게" 약속한다', effects: { mental: 4 }, npcEffects: [{ npcId: 'siwoo', intimacyChange: 8 }], message: '"…잊는 게 나아. 자리 기억하는 사람이 제일 오래 거기 묶여 서 있거든. 나처럼." 처음으로 먼저 손을 내밀어 악수한다.', timeCost: 1, memorySlotDraft: { category: 'reconciliation', importance: 8, toneTag: 'warm', recallText: '한 동이 다 올라선 자리, 짚는 곳마다 네가 있었다.', npcIds: ['siwoo'] } },
      { text: '"너랑 본 자리들이 제일 좋았어" 마음을 연다', effects: { mental: 4 }, npcEffects: [{ npcId: 'siwoo', intimacyChange: 8 }], message: '시우가 처음이자 마지막으로 똑바로 웃는다. "…나도." 시선을 안 돌린다.', timeCost: 1, memorySlotDraft: { category: 'reconciliation', importance: 8, toneTag: 'warm', recallText: '한 동이 다 올라선 자리, 짚는 곳마다 네가 있었다.', npcIds: ['siwoo'] } },
      { text: '"네가 진짜로 뭘 세우면, 그 앞에 꼭 서 있을게" 미래를 건다', effects: { mental: 3 }, npcEffects: [{ npcId: 'siwoo', intimacyChange: 7 }], message: '"…세워야지. 그땐 네 설 자리부터—" 말을 안 맺고, 텀블러를 내밀었다가 이번엔 안 돌려받는다.', timeCost: 1, memorySlotDraft: { category: 'reconciliation', importance: 8, toneTag: 'warm', recallText: '한 동이 다 올라선 자리, 짚는 곳마다 네가 있었다.', npcIds: ['siwoo'] } },
    ],
  },
  // ===================== 강예린 (yerin) — 고1~고3, 입시 전략가·효율의 언어 / 미산정 =====================
  // intro(단가표)가 t25를 흡수. 회계 콜백: intro ??? → t58 자소서 ??? → t68 미수금.
  {
    id: 'yerin-only-sample',
    reach: { npc: 'yerin', tier: 40, year: 5 },
    title: '표본이 너밖에 없어',
    description: '점심시간, 빈 교실. 예린이 휴대폰으로 학과 경쟁률을 빠르게 넘기다, 화면을 끄고 책상에 엎어둔다. 평소답지 않게 손이 잠깐 멈춰 있다. 창밖 운동장에서 애들이 우르르 몰려 웃는 소리가 넘어온다. 예린은 그쪽을 일부러 안 본다.\n예린: "나 너랑 있을 때만 산출을 안 돌려. (말이 빨라진다 — 스스로 멈춘다) …표본이 너밖에 없어서."',
    speakers: ['yerin'],
    location: 'classroom',
    background: 'classroom_high_afternoon',
    condition: (s) => { const n = s.npcs.find(x => x.id === 'yerin'); return !!n?.met && n.intimacy >= 40 && s.year === 5 && !s.isVacation; },
    choices: [
      { text: '"산출 까먹는 거, 나쁜 거 아니야" 가볍게 받는다', effects: { mental: 2 }, npcEffects: [{ npcId: 'yerin', intimacyChange: 6 }], message: '예린이 답 대신 엎어둔 휴대폰 위에 손을 얹었다 뗀다. "…무게가 안 나와." 그러곤 빈 책상을 손끝으로 한 번 쓸고 만다.', timeCost: 1, memorySlotDraft: { category: 'discovery', importance: 6, toneTag: 'melancholy', recallText: '표본이 하나뿐이라 끝내 무게가 안 나오던 산출.', npcIds: ['yerin'] } },
      { text: '"운동장, 한 번 안 봐?" 웃음소리 쪽을 가리킨다', effects: { social: 1 }, npcEffects: [{ npcId: 'yerin', intimacyChange: 5 }], message: '예린이 끝내 그쪽을 안 본다. 휴대폰을 더 멀리 민다. "…저긴 들어가는 순간 등수가 매겨지잖아." 거기서 끊는다.', timeCost: 1 },
      { text: '아무 말 없이 같이 엎어둔 휴대폰을 본다', effects: { mental: 1 }, npcEffects: [{ npcId: 'yerin', intimacyChange: 6 }], message: '둘 다 운동장 소리만 듣는다. "…이런 건 산출이 안 나오는데." 그러면서 안 일어난다.', timeCost: 1 },
    ],
  },
  {
    id: 'yerin-stolen-material',
    reach: { npc: 'yerin', tier: 42, year: 6 },
    title: '가로챈 자료',
    description: '고2 수행평가 조별과제. 우리 조가 며칠 밤새 짠 발표 구성을, 예린이 자기 조 발표에 거의 그대로 먼저 써먹었다. 교사가 예린 조를 본보기로 칭찬한다. 박수 속에서 예린은 한 번도 이쪽을 안 본다. 복도에서 마주치자 피하지는 않는데, 변명하려 입을 열었다 다물고 창밖으로 시선을 돌린다.\n예린: (한참 침묵 후) "미안하다고 하면 봐줄 거야? …안 봐줄 거잖아. 그럼 사과는 원가만 나가고 회수가 없어. …그 표정. 그건 단가가 안 나와. 얼마를 물어줘야 없어지는지를, 모르겠어."',
    speakers: ['yerin'],
    location: 'hallway',
    background: 'classroom_high',
    condition: (s) => { const n = s.npcs.find(x => x.id === 'yerin'); return !!n?.met && n.intimacy >= 42 && s.year === 6 && !s.isVacation; },
    choices: [
      { text: '"실망했어" 한마디만 남기고 돌아선다', effects: { mental: -1 }, npcEffects: [{ npcId: 'yerin', intimacyChange: -5 }], message: '예린이 끝내 눈을 못 맞춘다. 등 뒤로 작게 "…실망은, 기대가 있어야 하는 거잖아." 이후 예린은 졸업까지 다시는 먼저 다가오지 않는다.', timeCost: 1, memorySlotDraft: { category: 'betrayal', importance: 7, toneTag: 'regret', recallText: '기대가 있어야 실망도 한다던, 회수 없는 사과 한 줄.', npcIds: ['yerin'] } },
      { text: '"이겨서 좋아?" 침묵을 강제한다', effects: { mental: -1 }, npcEffects: [{ npcId: 'yerin', intimacyChange: 0 }], message: '예린이 대답을 못 한다. 칭찬받은 발표 자료를 한 번 본다. 한참 뒤 "…좋아야 하는데." 말끝이 식는다.', timeCost: 1, memorySlotDraft: { category: 'betrayal', importance: 7, toneTag: 'regret', recallText: '기대가 있어야 실망도 한다던, 회수 없는 사과 한 줄.', npcIds: ['yerin'] } },
      { text: '"한 번은 빚으로 달아둘게. 딱 한 번만"', effects: { mental: 1 }, npcEffects: [{ npcId: 'yerin', intimacyChange: 4 }], message: '예린이 처음으로 말문이 막힌다. "…왜 빚으로 해줘. 손절하면 깔끔한데." 부채감으로 관계가 끈적해지되, 예린은 그 빚을 스스로 못 갚는다.', timeCost: 1, memorySlotDraft: { category: 'betrayal', importance: 7, toneTag: 'regret', recallText: '기대가 있어야 실망도 한다던, 회수 없는 사과 한 줄.', npcIds: ['yerin'] } },
    ],
  },
  {
    id: 'yerin-receipt',
    reach: { npc: 'yerin', tier: 55, year: 6 },
    title: '가방 안의 영수증',
    description: '방과후 카페. 예린이 화장실 간 사이, 의자 밑에 영수증 한 장이 떨어져 있다 — 늘 들고 다니던 비싼 브랜드 가방이 아니라, 같은 디자인의 보세 제품을 산 영수증이다. 돌아온 예린이 그걸 보고 처음으로 표정 관리에 실패한다. 줍지도 못한 채 영수증을 발끝으로 더 깊이 밀어 가리고, 화제를 꺼낸다.\n예린: "…그거 됐고. 너 다음 주 수행 정리했어? 마감 금요일이야— (스스로 말 빨라진 걸 듣고 멈춘다) 진짜처럼 보이면 라인이 짜져. 여기서 약점 한 줄 새면, 내 단가가 통째로 깎여."',
    speakers: ['yerin'],
    location: 'cafe',
    background: 'cafe_study',
    condition: (s) => { const n = s.npcs.find(x => x.id === 'yerin'); return !!n?.met && n.intimacy >= 55 && s.year === 6; },
    choices: [
      { text: '"나한테까지 라인 안 짜도 돼" 가방을 가만히 본다', effects: { mental: 2 }, npcEffects: [{ npcId: 'yerin', intimacyChange: 7 }], message: '예린의 말이 멈춘다. 영수증을 가린 발을 치우지도, 줍지도 못한다. "…너한테까지, 라고 하지 마. 그럼 진짜 약점이 되잖아."', timeCost: 1, memorySlotDraft: { category: 'discovery', importance: 6, toneTag: 'melancholy', recallText: '발끝으로 밀어 가렸다 끝내 못 줍던 카페 바닥의 영수증.', npcIds: ['yerin'] } },
      { text: '"그 영수증, 나한텐 마이너스로 안 잡히는데" 그 애 회계로 받는다', effects: { mental: 1 }, npcEffects: [{ npcId: 'yerin', intimacyChange: 6 }], message: '예린의 눈빛이 흔들린다. 영수증을 가렸던 발끝이 슬쩍 떨어진다. 줍지도 다시 가리지도 않고, 그냥 거기 둔 채로 한참을 가만있는다.', timeCost: 1, memorySlotDraft: { category: 'discovery', importance: 6, toneTag: 'melancholy', recallText: '발끝으로 밀어 가렸다 끝내 못 줍던 카페 바닥의 영수증.', npcIds: ['yerin'] } },
      { text: '말없이 영수증을 주워 가방에 넣어준다', effects: { social: 1 }, npcEffects: [{ npcId: 'yerin', intimacyChange: 5 }], message: '예린이 한참 본다. "…빚 하나 진 거다." 익숙한 거래로 도망친다. 손은 가방끈을 꽉 쥔다. (이 빚도 끝내 회수 안 한다.)', timeCost: 1, memorySlotDraft: { category: 'discovery', importance: 6, toneTag: 'melancholy', recallText: '발끝으로 밀어 가렸다 끝내 못 줍던 카페 바닥의 영수증.', npcIds: ['yerin'] } },
    ],
  },
  {
    id: 'yerin-undroppable-line',
    reach: { npc: 'yerin', tier: 58, year: 7 },
    title: '단가가 안 떨어지는 줄',
    description: '고3 여름. 야자 끝난 교실. 예린이 처음으로 대가를 안 걸고 부탁한다. "내 자소서 좀 봐줄래. …아니, 봐줘." 늘 완벽하게 짜오던 애가 초안을 통째로 내민다. 모든 칸이 빼곡한데, 장래희망 줄에만 단가란처럼 \'???\'가 적혀 있고, 그 위로 두 줄이 그어져 있다 — 처음 만난 날 내 이름 줄에 했던 그 처리 그대로다.\n예린: "나 그동안 \'단가 나오는 거\'만 줄 세웠지, \'되고 싶은 거\'는 한 줄도 산출을 못 돌려봤더라. 너는 사람을 손익으로 안 매기잖아. …그 셈법이, 지금은 나한테 필요해."',
    speakers: ['yerin'],
    location: 'classroom',
    background: 'classroom_high_afternoon',
    condition: (s) => { const n = s.npcs.find(x => x.id === 'yerin'); return !!n?.met && n.intimacy >= 58 && s.year === 7 && !s.isVacation; },
    choices: [
      { text: '"나는 그 줄, 아직도 단가 한 번 못 내봤는데" 내 미정산 줄을 같이 펼친다', effects: { mental: 2 }, npcEffects: [{ npcId: 'yerin', intimacyChange: 7 }], message: '예린이 펜을 다시 쥐고 첫 글자를 대보다가, 두 줄에 똑같이 ???가 그어진 걸 보고 펜을 놓는다. "…너도 적자였구나. 그럼 이건 누구 손해로 다는 거야."', timeCost: 1, memorySlotDraft: { category: 'discovery', importance: 7, toneTag: 'resolve', recallText: '될 수 있는 것만 줄 세우다 적자만 뜨던 장래희망의 ???.', npcIds: ['yerin'] } },
      { text: '"줄 세우기 전에, 뭐 할 때 시간 가는 줄 몰랐어?" 근본을 묻는다', effects: { mental: 1 }, npcEffects: [{ npcId: 'yerin', intimacyChange: 7 }], message: '예린이 오래 침묵한다. "…기억이 안 나." 거기서 끊는다. ??? 위에 펜을 댔다 뗀다.', timeCost: 1, memorySlotDraft: { category: 'discovery', importance: 7, toneTag: 'resolve', recallText: '될 수 있는 것만 줄 세우다 적자만 뜨던 장래희망의 ???.', npcIds: ['yerin'] } },
      { text: '"이 줄, 결산 안 하고 그냥 둬볼래?" 그 애 셈을 비튼다', effects: { mental: 2 }, npcEffects: [{ npcId: 'yerin', intimacyChange: 6 }], message: '예린이 그어둔 ??? 옆에 펜을 한참 댔다 뗀다 — 처음 내 줄을 미산정으로 보류하던 그 손이다. "…결산을 미루는 회계는, 처음 본다."', timeCost: 1, memorySlotDraft: { category: 'discovery', importance: 7, toneTag: 'resolve', recallText: '될 수 있는 것만 줄 세우다 적자만 뜨던 장래희망의 ???.', npcIds: ['yerin'] } },
    ],
  },
  {
    id: 'yerin-not-a-trade',
    reach: { npc: 'yerin', tier: 68, year: 7 },
    title: '이번엔 교환 아니야',
    description: '졸업 직전, 합격자 발표 시즌. 다들 예린에게 마지막 정보만 받아가고 흩어진 뒤, 교문 앞에 예린이 혼자 기다리고 있다. 손엔 반 전체를 단가로 적어온 장부. 예린이 노트를 펴서, 다른 애들 줄은 전부 결산선을 그어 닫는다. 마지막으로 내 이름 줄 — 3년 내내 미산정으로 보류돼 있던 그 줄 — 에 펜을 댔다가, 결산선을 긋지 않는다. 대신 여백에 회계 약어 하나만 적는다: \'미수금\'.\n예린: "네 줄만 안 닫았어. …이번엔 교환 아니야. (왜냐고 물으면, 한참 있다가) 근거… 없어. 매길 무게가 안 나와. 닫으면 끝나는데, 이 줄만 못 닫겠어서."',
    speakers: ['yerin'],
    location: 'school_gate',
    background: 'school_gate_high',
    condition: (s) => { const n = s.npcs.find(x => x.id === 'yerin'); return !!n?.met && n.intimacy >= 68 && s.year === 7; },
    choices: [
      { text: '"근거 없이? 너답지 않게" 웃으며 그 줄을 같이 본다', effects: { mental: 3 }, npcEffects: [{ npcId: 'yerin', intimacyChange: 8 }], message: '예린이 \'미수금\' 옆 빈자리를 한 번 본다. "…그러게. 평생 결산으로 살았는데." 처음으로 산출 없이 픽 웃는다. 끝내 안 닫힌 줄 하나가 예린의 장부에 영영 남는다.', timeCost: 1, memorySlotDraft: { category: 'reconciliation', importance: 8, toneTag: 'warm', recallText: '다른 줄은 다 닫고 내 줄만 미수금으로 남겨두던 예린.', npcIds: ['yerin'] } },
      { text: '"이 줄, 끝내 결산 안 했네" 미수금을 짚는다', effects: { mental: 2 }, npcEffects: [{ npcId: 'yerin', intimacyChange: 7 }], message: '예린이 펜을 들어 결산선을 그으려다, 손이 멈춘다. 끝내 못 닫는다. "…닫으면 또 단가가 되니까." 미수금인 채로 노트를 덮는다.', timeCost: 1, memorySlotDraft: { category: 'reconciliation', importance: 8, toneTag: 'warm', recallText: '다른 줄은 다 닫고 내 줄만 미수금으로 남겨두던 예린.', npcIds: ['yerin'] } },
      { text: '"넌 끝까지 다 결산해야 편한 애잖아. 그 줄도 닫아" 닫으라고 돌려보낸다', effects: { mental: -1 }, npcEffects: [{ npcId: 'yerin', intimacyChange: 0 }], message: '예린이 0.5초 멈췄다, 펜으로 그 줄에 결산선을 긋고 노트를 가방에 넣는다. "…그래. 그게 너답네." 더는 안 붙잡는다. 그 줄은 닫힌 채 안 건너온다.', timeCost: 1, memorySlotDraft: { category: 'failure', importance: 8, toneTag: 'regret', recallText: '끝내 내 줄까지 결산선을 긋고 닫아버린 예린.', npcIds: ['yerin'] } },
    ],
  },
] satisfies readonly GameEvent[];
